const WORD_BANK = [
  { word: "cat", definition: "A small pet that purrs and likes to chase things." },
  { word: "dog", definition: "A pet that barks and can be a good friend." },
  { word: "bird", definition: "An animal with feathers and wings." },
  { word: "fish", definition: "An animal that lives in water and swims." },
  { word: "cow", definition: "A farm animal that gives milk." },
  { word: "pig", definition: "A farm animal with a round body and curly tail." },
  { word: "horse", definition: "A large animal people can ride." },
  { word: "sheep", definition: "A farm animal with a thick wool coat." },
  { word: "goat", definition: "A farm animal that can climb and may have horns." },
  { word: "duck", definition: "A bird with a flat bill that likes water." },
  { word: "chicken", definition: "A farm bird that lays eggs." },
  { word: "rabbit", definition: "A small animal with long ears and a short tail." },
  { word: "mouse", definition: "A very small animal with a long tail." },
  { word: "bear", definition: "A large wild animal with fur and strong paws." },
  { word: "lion", definition: "A big wild cat known for its loud roar." },
  { word: "tiger", definition: "A big wild cat with dark stripes." },
  { word: "zebra", definition: "A horse-like animal with black-and-white stripes." },
  { word: "monkey", definition: "An animal that climbs and swings in trees." },
  { word: "elephant", definition: "A huge animal with a long trunk." },
  { word: "giraffe", definition: "A very tall animal with a long neck." },
  { word: "frog", definition: "A small animal that hops and lives near water." },
  { word: "snake", definition: "A long animal with no legs." },
  { word: "turtle", definition: "An animal with a hard shell on its back." },
  { word: "whale", definition: "A very large animal that lives in the ocean." },
  { word: "shark", definition: "A strong sea animal with sharp teeth." },
  { word: "dolphin", definition: "A smart sea animal that leaps from the water." },
  { word: "octopus", definition: "A sea animal with eight arms." },
  { word: "crab", definition: "A sea animal with claws and a hard shell." },
  { word: "bee", definition: "A flying insect that makes honey." },
  { word: "ant", definition: "A tiny insect that lives in busy groups." },
  { word: "butterfly", definition: "A colorful insect with large wings." },
  { word: "spider", definition: "A small creature with eight legs that spins webs." },
  { word: "worm", definition: "A long, soft animal with no legs." },
  { word: "owl", definition: "A bird that is often awake at night." },
  { word: "eagle", definition: "A large bird with strong wings and sharp sight." },
  { word: "hawk", definition: "A bird that hunts small animals from the sky." },
  { word: "fox", definition: "A wild animal with a bushy tail." },
  { word: "wolf", definition: "A wild animal that lives and hunts in groups." },
  { word: "deer", definition: "A gentle wild animal with long legs." },
  { word: "moose", definition: "A very large deer-like animal with big antlers." },
  { word: "goose", definition: "A water bird with a long neck." },
  { word: "swan", definition: "A large water bird known for its graceful neck." },
  { word: "turkey", definition: "A large bird with a fan-shaped tail." },
  { word: "donkey", definition: "A sturdy animal like a small horse." },
  { word: "camel", definition: "A desert animal with humps on its back." },
  { word: "panda", definition: "A black-and-white bear that eats bamboo." },
  { word: "koala", definition: "A tree-dwelling animal from Australia." },
  { word: "kangaroo", definition: "An Australian animal that hops and carries babies in a pouch." },
  { word: "leopard", definition: "A big wild cat with dark spots." },
  { word: "cheetah", definition: "A very fast big cat." },
  { word: "rhino", definition: "A huge animal with one or two horns on its nose." },
  { word: "hippo", definition: "A very large animal that spends much time in water." },
  { word: "otter", definition: "A playful animal that swims and floats in water." },
  { word: "seal", definition: "A smooth sea animal that rests on shore." },
  { word: "penguin", definition: "A black-and-white bird that cannot fly but swims well." },
  { word: "parrot", definition: "A bright bird that can copy sounds." },
  { word: "peacock", definition: "A bird with a large colorful tail." },
  { word: "flamingo", definition: "A tall pink bird with long legs." },
  { word: "lizard", definition: "A small scaly animal with four legs." },
  { word: "gecko", definition: "A tiny lizard that can climb walls." },
  { word: "iguana", definition: "A large lizard with a long tail." },
  { word: "alligator", definition: "A large reptile with a wide snout." },
  { word: "crocodile", definition: "A large reptile with strong jaws that lives near water." },
  { word: "bat", definition: "A flying animal that is awake at night." },
  { word: "squirrel", definition: "A small furry animal that climbs trees and gathers nuts." },
  { word: "chipmunk", definition: "A small striped animal with cheek pouches." },
  { word: "hamster", definition: "A small furry pet with tiny paws." },
  { word: "gerbil", definition: "A small pet animal with a long tail." },
  { word: "hedgehog", definition: "A small animal covered with sharp spines." },
  { word: "raccoon", definition: "A furry animal with a mask-like face." },
  { word: "skunk", definition: "A black-and-white animal known for a strong smell." },
  { word: "badger", definition: "A strong digging animal that lives underground." },
  { word: "beaver", definition: "An animal that builds dams in streams." },
  { word: "mole", definition: "A small animal that digs tunnels underground." },
  { word: "snail", definition: "A slow animal with a shell on its back." },
  { word: "slug", definition: "A soft, slow animal with no shell." },
  { word: "beetle", definition: "An insect with a hard outer covering." },
  { word: "ladybug", definition: "A tiny spotted beetle often seen in gardens." },
  { word: "grasshopper", definition: "An insect with long back legs for jumping." },
  { word: "dragonfly", definition: "A fast flying insect with long wings." },
  { word: "mosquito", definition: "A tiny flying insect that bites." },
  { word: "fly", definition: "A small flying insect found in many places." },
  { word: "moth", definition: "An insect like a butterfly that often flies at night." },
  { word: "shrimp", definition: "A small sea animal with a curved body." },
  { word: "lobster", definition: "A sea animal with claws and a hard shell." },
  { word: "clam", definition: "A shell animal that lives in sand or mud." },
  { word: "oyster", definition: "A shell animal that lives in water and can make pearls." },
  { word: "starfish", definition: "A sea animal shaped like a star." },
  { word: "seahorse", definition: "A tiny sea animal with a curled tail." },
  { word: "jellyfish", definition: "A soft sea animal with trailing arms." },
  { word: "apple", definition: "A round fruit that can be red, green, or yellow." },
  { word: "banana", definition: "A long yellow fruit with a peel." },
  { word: "orange", definition: "A juicy fruit with a thick skin." },
  { word: "grape", definition: "A small round fruit that grows in bunches." },
  { word: "pear", definition: "A sweet fruit that is narrow at the top and wide at the bottom." },
  { word: "peach", definition: "A soft fruit with fuzzy skin and a pit inside." },
  { word: "plum", definition: "A small smooth fruit with a pit." },
  { word: "cherry", definition: "A small round fruit with a pit and stem." },
  { word: "lemon", definition: "A sour yellow fruit." },
  { word: "lime", definition: "A small green fruit with a sour taste." },
  { word: "melon", definition: "A large fruit with lots of juicy flesh inside." },
  { word: "berry", definition: "A small juicy fruit." },
  { word: "mango", definition: "A sweet tropical fruit with a large pit." },
  { word: "pineapple", definition: "A tropical fruit with rough skin and a spiky top." },
  { word: "coconut", definition: "A hard tropical fruit with liquid and white flesh inside." },
  { word: "papaya", definition: "A soft tropical fruit with many black seeds." },
  { word: "kiwi", definition: "A small brown fruit with green flesh inside." },
  { word: "apricot", definition: "A small soft fruit with a pit." },
  { word: "carrot", definition: "A long orange root vegetable." },
  { word: "potato", definition: "A starchy vegetable that grows underground." },
  { word: "tomato", definition: "A soft red fruit often used like a vegetable." },
  { word: "corn", definition: "A yellow food that grows in rows on a cob." },
  { word: "pea", definition: "A small round green vegetable." },
  { word: "bean", definition: "A seed often eaten as food." },
  { word: "lettuce", definition: "A leafy green used in salads." },
  { word: "onion", definition: "A round vegetable with many layers inside." },
  { word: "garlic", definition: "A strong-smelling food made of cloves." },
  { word: "pepper", definition: "A vegetable that can be sweet or spicy." },
  { word: "broccoli", definition: "A green vegetable with a tree-like top." },
  { word: "cucumber", definition: "A long green vegetable with watery flesh." },
  { word: "pumpkin", definition: "A large orange squash used in fall." },
  { word: "squash", definition: "A vegetable with hard skin and soft inside." },
  { word: "cabbage", definition: "A leafy vegetable that grows in a round head." },
  { word: "celery", definition: "A crunchy green stalk often eaten raw." },
  { word: "spinach", definition: "A leafy green vegetable." },
  { word: "radish", definition: "A small root vegetable with a peppery taste." },
  { word: "beet", definition: "A round root vegetable that is often deep red." },
  { word: "turnip", definition: "A round root vegetable with white or purple skin." },
  { word: "mushroom", definition: "A soft fungus often used in cooking." },
  { word: "olive", definition: "A small fruit often used for oil or snacks." },
  { word: "avocado", definition: "A soft green fruit with a large pit." },
  { word: "bread", definition: "A baked food made from flour." },
  { word: "cake", definition: "A sweet baked treat for parties and desserts." },
  { word: "cookie", definition: "A small sweet baked treat." },
  { word: "pie", definition: "A baked dish with crust and filling." },
  { word: "pizza", definition: "A baked flat food with sauce and toppings." },
  { word: "sandwich", definition: "Food made by putting filling between bread." },
  { word: "soup", definition: "A warm food made with liquid." },
  { word: "salad", definition: "A mix of raw vegetables or other foods." },
  { word: "egg", definition: "A food with a shell that comes from birds." },
  { word: "cheese", definition: "A food made from milk." },
  { word: "milk", definition: "A white drink that comes from animals or plants." },
  { word: "juice", definition: "A drink made from fruit or vegetables." },
  { word: "water", definition: "A clear drink that people need to live." },
  { word: "pasta", definition: "Food made from dough and boiled in water." },
  { word: "noodle", definition: "A long thin piece of cooked dough." },
  { word: "rice", definition: "Small grains cooked and eaten as food." },
  { word: "cereal", definition: "A breakfast food often eaten with milk." },
  { word: "pancake", definition: "A flat round breakfast food cooked on a pan." },
  { word: "waffle", definition: "A breakfast food with square pockets." },
  { word: "muffin", definition: "A small baked bread or cake." },
  { word: "biscuit", definition: "A soft baked bread roll or a crisp treat, depending on where you live." },
  { word: "cracker", definition: "A thin crunchy snack." },
  { word: "yogurt", definition: "A creamy food made from milk." },
  { word: "butter", definition: "A soft yellow food spread made from cream." },
  { word: "jam", definition: "A sweet fruit spread." },
  { word: "jelly", definition: "A sweet spread made from fruit juice." },
  { word: "honey", definition: "A sweet sticky food made by bees." },
  { word: "syrup", definition: "A thick sweet liquid." },
  { word: "candy", definition: "A sweet treat made with sugar." },
  { word: "chocolate", definition: "A sweet treat made from cocoa." },
  { word: "popcorn", definition: "Corn that puffs up when heated." },
  { word: "pretzel", definition: "A baked snack twisted into a shape." },
  { word: "taco", definition: "A folded shell filled with food." },
  { word: "burrito", definition: "A rolled tortilla filled with food." },
  { word: "burger", definition: "A sandwich with a patty inside." },
  { word: "sausage", definition: "A tube-shaped food made from seasoned meat or other fillings." },
  { word: "bacon", definition: "Thin strips of salty meat." },
  { word: "meatball", definition: "A small round ball made from ground meat or another mix." },
  { word: "wafer", definition: "A thin crisp sweet snack." },
  { word: "fries", definition: "Thin pieces of potato cooked until crisp." },
  { word: "oatmeal", definition: "A warm breakfast made from oats." },
  { word: "pudding", definition: "A soft sweet dessert." },
  { word: "sundae", definition: "Ice cream served with toppings." },
  { word: "cupcake", definition: "A small cake baked in a paper cup." },
  { word: "donut", definition: "A sweet fried or baked ring-shaped treat." },
  { word: "chair", definition: "A seat for one person." },
  { word: "table", definition: "A flat piece of furniture with legs." },
  { word: "desk", definition: "A table used for work or school." },
  { word: "bed", definition: "Furniture used for sleeping." },
  { word: "pillow", definition: "A soft cushion for your head." },
  { word: "blanket", definition: "A warm cover used on a bed." },
  { word: "couch", definition: "A soft seat for more than one person." },
  { word: "lamp", definition: "Something that gives light." },
  { word: "clock", definition: "Something that shows time." },
  { word: "mirror", definition: "A smooth surface that shows your reflection." },
  { word: "door", definition: "A panel that opens and closes an entrance." },
  { word: "window", definition: "An opening with glass that lets in light." },
  { word: "wall", definition: "The side part of a room or building." },
  { word: "floor", definition: "The bottom surface you walk on." },
  { word: "roof", definition: "The top covering of a building." },
  { word: "house", definition: "A building where people live." },
  { word: "home", definition: "The place where someone lives and feels they belong." },
  { word: "room", definition: "A space inside a building." },
  { word: "kitchen", definition: "A room where food is made." },
  { word: "bathroom", definition: "A room with a sink, toilet, or shower." },
  { word: "bedroom", definition: "A room for sleeping." },
  { word: "garage", definition: "A place where cars or tools are kept." },
  { word: "garden", definition: "A place where plants or flowers are grown." },
  { word: "fence", definition: "A barrier around a yard or area." },
  { word: "bucket", definition: "A container with a handle." },
  { word: "basket", definition: "A container used to carry things." },
  { word: "bottle", definition: "A container for liquids." },
  { word: "cup", definition: "A small container used for drinking." },
  { word: "plate", definition: "A flat dish for food." },
  { word: "bowl", definition: "A round dish with deep sides." },
  { word: "spoon", definition: "A tool for eating or stirring with a round end." },
  { word: "fork", definition: "A tool for eating with pointed ends." },
  { word: "knife", definition: "A tool with a blade for cutting." },
  { word: "napkin", definition: "A piece of cloth or paper used while eating." },
  { word: "towel", definition: "A cloth used for drying." },
  { word: "soap", definition: "Something used for washing." },
  { word: "brush", definition: "A tool with bristles for cleaning or styling." },
  { word: "comb", definition: "A tool with teeth for fixing hair." },
  { word: "toothbrush", definition: "A small brush used to clean teeth." },
  { word: "backpack", definition: "A bag carried on your back." },
  { word: "pencil", definition: "A tool used for writing that can be erased." },
  { word: "pen", definition: "A writing tool that uses ink." },
  { word: "crayon", definition: "A colored stick used for drawing." },
  { word: "marker", definition: "A pen-like tool with strong color." },
  { word: "eraser", definition: "Something used to rub out pencil marks." },
  { word: "ruler", definition: "A straight tool used for measuring." },
  { word: "notebook", definition: "Pages bound together for writing." },
  { word: "paper", definition: "Thin material used for writing or drawing." },
  { word: "book", definition: "Pages with words or pictures bound together." },
  { word: "story", definition: "A tale with characters and events." },
  { word: "map", definition: "A drawing that shows where places are." },
  { word: "globe", definition: "A round model of Earth." },
  { word: "toy", definition: "Something made for play." },
  { word: "game", definition: "An activity with rules for fun." },
  { word: "puzzle", definition: "A problem or toy you solve by thinking." },
  { word: "block", definition: "A solid piece used for building or stacking." },
  { word: "ball", definition: "A round object used in play and sports." },
  { word: "kite", definition: "Something that flies in the wind on a string." },
  { word: "rope", definition: "A thick cord used for tying or pulling." },
  { word: "string", definition: "A thin cord." },
  { word: "tape", definition: "A sticky strip used to hold things together." },
  { word: "glue", definition: "A sticky substance used to join things." },
  { word: "scissors", definition: "A tool with two blades for cutting." },
  { word: "hammer", definition: "A tool used for pounding nails." },
  { word: "nail", definition: "A small metal pin used in building." },
  { word: "screw", definition: "A metal fastener with a spiral shape." },
  { word: "wrench", definition: "A tool used to tighten or loosen nuts and bolts." },
  { word: "shovel", definition: "A tool used for digging." },
  { word: "rake", definition: "A tool used to gather leaves or smooth soil." },
  { word: "broom", definition: "A tool used for sweeping." },
  { word: "mop", definition: "A tool used for washing floors." },
  { word: "vacuum", definition: "A machine that cleans by sucking up dirt." },
  { word: "phone", definition: "A device used to call or message people." },
  { word: "camera", definition: "A device used to take pictures." },
  { word: "radio", definition: "A device that plays broadcasts and music." },
  { word: "speaker", definition: "Something that plays sound out loud." },
  { word: "screen", definition: "A flat surface that shows pictures or words." },
  { word: "keyboard", definition: "A set of keys used to type." },
  { word: "remote", definition: "A small device used to control something from far away." },
  { word: "battery", definition: "A small power source for devices." },
  { word: "charger", definition: "Something that gives power to a device again." },
  { word: "helmet", definition: "Hard gear worn to protect the head." },
  { word: "umbrella", definition: "Something that opens to keep off rain." },
  { word: "wallet", definition: "A small holder for money and cards." },
  { word: "pocket", definition: "A small cloth space in clothing used to hold things." },
  { word: "zipper", definition: "A fastener with two rows that slide together." },
  { word: "button", definition: "A small fastener on clothing or a part you press." },
  { word: "key", definition: "A tool used to open a lock." },
  { word: "lock", definition: "Something that keeps a door, box, or gate closed." },
  { word: "chain", definition: "Linked metal rings joined together." },
  { word: "bag", definition: "A soft container used to carry things." },
  { word: "box", definition: "A container with sides and a lid or opening." },
  { word: "gift", definition: "Something given to another person." },
  { word: "coin", definition: "A piece of metal money." },
  { word: "school", definition: "A place where children go to learn." },
  { word: "classroom", definition: "A room where lessons happen." },
  { word: "library", definition: "A place with many books to read or borrow." },
  { word: "park", definition: "An outdoor place for play or rest." },
  { word: "playground", definition: "An outdoor area with equipment for children to play on." },
  { word: "store", definition: "A place where things are sold." },
  { word: "market", definition: "A place where many goods or foods are sold." },
  { word: "bakery", definition: "A place where bread and sweet treats are made or sold." },
  { word: "farm", definition: "A place where crops are grown and animals are kept." },
  { word: "zoo", definition: "A place where people can see animals." },
  { word: "beach", definition: "Sandy or rocky land beside water." },
  { word: "river", definition: "A long moving stream of water." },
  { word: "lake", definition: "A large area of water surrounded by land." },
  { word: "pond", definition: "A small still body of water." },
  { word: "stream", definition: "A small flowing body of water." },
  { word: "ocean", definition: "A huge body of salt water." },
  { word: "island", definition: "Land with water all around it." },
  { word: "forest", definition: "A large area filled with trees." },
  { word: "jungle", definition: "A thick hot forest with many plants." },
  { word: "desert", definition: "A very dry land with little rain." },
  { word: "mountain", definition: "Very high land that rises above the ground around it." },
  { word: "hill", definition: "A raised area of land smaller than a mountain." },
  { word: "valley", definition: "Low land between hills or mountains." },
  { word: "cave", definition: "A hollow place inside rock or earth." },
  { word: "cliff", definition: "A very steep rock face." },
  { word: "waterfall", definition: "Water falling from a high place." },
  { word: "tree", definition: "A tall plant with a trunk and branches." },
  { word: "bush", definition: "A low plant with many branches." },
  { word: "flower", definition: "The colorful part of a plant." },
  { word: "grass", definition: "Short green plants that cover the ground." },
  { word: "leaf", definition: "The flat green part of many plants." },
  { word: "root", definition: "The part of a plant that grows underground." },
  { word: "branch", definition: "A part that grows out from a tree trunk." },
  { word: "seed", definition: "The small part of a plant that can grow into a new one." },
  { word: "rock", definition: "A hard piece of stone." },
  { word: "stone", definition: "Hard natural material from the ground." },
  { word: "cloud", definition: "A white or gray shape in the sky made of tiny drops of water." },
  { word: "rain", definition: "Water that falls from clouds." },
  { word: "snow", definition: "Soft white ice crystals that fall from the sky." },
  { word: "wind", definition: "Moving air." },
  { word: "storm", definition: "Weather with strong wind, rain, or thunder." },
  { word: "thunder", definition: "The loud sound heard during a storm." },
  { word: "lightning", definition: "A bright flash in the sky during a storm." },
  { word: "rainbow", definition: "A band of colors seen in the sky after rain." },
  { word: "sun", definition: "The star that gives Earth light and warmth." },
  { word: "moon", definition: "The round object that moves around Earth at night." },
  { word: "star", definition: "A bright point of light in the night sky." },
  { word: "planet", definition: "A large round world in space." },
  { word: "space", definition: "The huge area beyond Earth." },
  { word: "road", definition: "A path for cars and other vehicles." },
  { word: "street", definition: "A road in a town or city." },
  { word: "bridge", definition: "A structure that goes over water or land to connect places." },
  { word: "tunnel", definition: "A passage that goes through or under something." },
  { word: "path", definition: "A way for walking." },
  { word: "trail", definition: "A path through woods, hills, or other nature." },
  { word: "sidewalk", definition: "The safe walkway beside a street." },
  { word: "town", definition: "A place where people live that is smaller than a city." },
  { word: "city", definition: "A large place where many people live and work." },
  { word: "village", definition: "A very small town." },
  { word: "country", definition: "A large land area that is its own nation." },
  { word: "airport", definition: "A place where airplanes take off and land." },
  { word: "station", definition: "A place where buses or trains stop." },
  { word: "harbor", definition: "A sheltered place where boats stay." },
  { word: "port", definition: "A place where ships load, unload, or stop." },
  { word: "camp", definition: "A place where people stay outdoors for a short time." },
  { word: "tent", definition: "A fabric shelter used outdoors." },
  { word: "castle", definition: "A large strong building where royalty once lived." },
  { word: "tower", definition: "A very tall building or part of one." },
  { word: "museum", definition: "A place where important objects are shown." },
  { word: "hospital", definition: "A place where sick or hurt people get care." },
  { word: "office", definition: "A place where people do work at desks." },
  { word: "church", definition: "A building where Christians gather to worship." },
  { word: "temple", definition: "A building used for worship in some religions." },
  { word: "theater", definition: "A place where plays or movies are shown." },
  { word: "stadium", definition: "A large place where sports or big events happen." },
  { word: "restaurant", definition: "A place where meals are made and served." },
  { word: "add", definition: "Put more in." },
  { word: "agree", definition: "Say yes to an idea." },
  { word: "allow", definition: "Let something happen." },
  { word: "answer", definition: "Say or write a reply." },
  { word: "arrive", definition: "Get to a place." },
  { word: "ask", definition: "Say you want to know something." },
  { word: "bake", definition: "Cook in an oven." },
  { word: "balance", definition: "Stay steady without falling." },
  { word: "bark", definition: "Make a dog sound." },
  { word: "bathe", definition: "Wash in water." },
  { word: "beam", definition: "Smile brightly." },
  { word: "beg", definition: "Ask strongly for something." },
  { word: "behave", definition: "Act in a good way." },
  { word: "blink", definition: "Open and close your eyes quickly." },
  { word: "bloom", definition: "Open into flowers." },
  { word: "blow", definition: "Push air." },
  { word: "blush", definition: "Turn pink from feeling shy." },
  { word: "boil", definition: "Heat until bubbling." },
  { word: "borrow", definition: "Take something to use and give back later." },
  { word: "bounce", definition: "Spring up after hitting a surface." },
  { word: "bow", definition: "Bend forward." },
  { word: "break", definition: "Make something come apart." },
  { word: "breathe", definition: "Take air in and out." },
  { word: "bring", definition: "Carry something to a place." },
  { word: "build", definition: "Make something." },
  { word: "bump", definition: "Hit lightly." },
  { word: "burn", definition: "Be on fire or hurt from heat." },
  { word: "bury", definition: "Put under the ground." },
  { word: "buy", definition: "Pay money for something." },
  { word: "call", definition: "Say or shout to someone." },
  { word: "care", definition: "Look after someone or something." },
  { word: "carry", definition: "Hold and move something." },
  { word: "carve", definition: "Cut into a shape." },
  { word: "catch", definition: "Grab something moving." },
  { word: "chase", definition: "Run after." },
  { word: "chat", definition: "Talk in a friendly way." },
  { word: "chew", definition: "Bite food again and again." },
  { word: "clap", definition: "Hit your hands together." },
  { word: "clean", definition: "Make tidy." },
  { word: "climb", definition: "Go up." },
  { word: "close", definition: "Shut." },
  { word: "coach", definition: "Teach and guide." },
  { word: "collect", definition: "Gather things together." },
  { word: "color", definition: "Add color to something." },
  { word: "compare", definition: "Look at how things are alike or different." },
  { word: "complain", definition: "Say you are not happy." },
  { word: "complete", definition: "Finish." },
  { word: "cook", definition: "Make food with heat." },
  { word: "cool", definition: "Make less warm." },
  { word: "copy", definition: "Make one like another." },
  { word: "count", definition: "Say numbers in order." },
  { word: "cover", definition: "Put something over the top." },
  { word: "crawl", definition: "Move low to the ground." },
  { word: "cross", definition: "Go from one side to another." },
  { word: "cry", definition: "Make tears." },
  { word: "dance", definition: "Move to music." },
  { word: "dare", definition: "Be brave enough to do something." },
  { word: "decide", definition: "Choose." },
  { word: "decorate", definition: "Make something look nicer." },
  { word: "deliver", definition: "Bring something to a place." },
  { word: "depend", definition: "Need someone or something." },
  { word: "describe", definition: "Tell what something is like." },
  { word: "design", definition: "Plan how something will look or work." },
  { word: "dig", definition: "Move dirt with your hands or a tool." },
  { word: "disagree", definition: "Say no to an idea." },
  { word: "discover", definition: "Find something new." },
  { word: "dive", definition: "Jump into water." },
  { word: "do", definition: "Perform an action." },
  { word: "draw", definition: "Make a picture." },
  { word: "dream", definition: "See pictures in your mind while sleeping." },
  { word: "dress", definition: "Put clothes on." },
  { word: "drink", definition: "Swallow a liquid." },
  { word: "drip", definition: "Fall in small drops." },
  { word: "drop", definition: "Let something fall." },
  { word: "dry", definition: "Make not wet." },
  { word: "dust", definition: "Clean away fine dirt." },
  { word: "eat", definition: "Put food in your mouth and swallow it." },
  { word: "echo", definition: "Repeat a sound." },
  { word: "end", definition: "Stop." },
  { word: "enjoy", definition: "Like something." },
  { word: "enter", definition: "Go in." },
  { word: "escape", definition: "Get away." },
  { word: "exercise", definition: "Move your body to get stronger." },
  { word: "explain", definition: "Make something easy to understand." },
  { word: "explore", definition: "Look around and discover." },
  { word: "face", definition: "Look toward." },
  { word: "fade", definition: "Slowly lose color or strength." },
  { word: "fail", definition: "Not succeed." },
  { word: "fall", definition: "Drop down." },
  { word: "fasten", definition: "Close or attach tightly." },
  { word: "feed", definition: "Give food to." },
  { word: "feel", definition: "Sense something." },
  { word: "fetch", definition: "Go get something." },
  { word: "fight", definition: "Try to hurt or beat." },
  { word: "fill", definition: "Make full." },
  { word: "find", definition: "Discover where something is." },
  { word: "finish", definition: "Complete." },
  { word: "fit", definition: "Be the right size." },
  { word: "fix", definition: "Make work again." },
  { word: "flap", definition: "Move up and down quickly." },
  { word: "float", definition: "Stay on top of water or in the air." },
  { word: "flood", definition: "Cover with lots of water." },
  { word: "flow", definition: "Move smoothly." },
  { word: "fly", definition: "Move through the air." },
  { word: "fold", definition: "Bend over." },
  { word: "follow", definition: "Go after." },
  { word: "fool", definition: "Trick someone." },
  { word: "force", definition: "Make something happen." },
  { word: "form", definition: "Make or shape." },
  { word: "found", definition: "Start and build something new." },
  { word: "freeze", definition: "Turn very cold and hard." },
  { word: "fry", definition: "Cook in hot oil." },
  { word: "gather", definition: "Bring together." },
  { word: "gaze", definition: "Look for a while." },
  { word: "get", definition: "Receive or reach." },
  { word: "giggle", definition: "Laugh in a light way." },
  { word: "give", definition: "Hand something to someone." },
  { word: "glance", definition: "Look quickly." },
  { word: "glow", definition: "Shine softly." },
  { word: "grab", definition: "Take quickly." },
  { word: "grin", definition: "Smile widely." },
  { word: "grip", definition: "Hold tightly." },
  { word: "groan", definition: "Make a low unhappy sound." },
  { word: "grow", definition: "Become bigger." },
  { word: "guess", definition: "Answer without knowing for sure." },
  { word: "guide", definition: "Lead the way." },
  { word: "hand", definition: "Give by using your hand." },
  { word: "hang", definition: "Be held from above." },
  { word: "happen", definition: "Take place." },
  { word: "hatch", definition: "Come out of an egg." },
  { word: "hate", definition: "Strongly dislike." },
  { word: "have", definition: "Own or hold." },
  { word: "head", definition: "Go toward a place." },
  { word: "heal", definition: "Get better." },
  { word: "hear", definition: "Notice sound." },
  { word: "help", definition: "Make something easier." },
  { word: "hide", definition: "Keep out of sight." },
  { word: "hike", definition: "Take a long walk outdoors." },
  { word: "hop", definition: "Jump in little steps." },
  { word: "hope", definition: "Want something good to happen." },
  { word: "hug", definition: "Hold someone close." },
  { word: "hum", definition: "Make a soft singing sound." },
  { word: "hunt", definition: "Look for." },
  { word: "hurry", definition: "Move fast." },
  { word: "imagine", definition: "Picture something in your mind." },
  { word: "improve", definition: "Make better." },
  { word: "include", definition: "Have as part of it." },
  { word: "increase", definition: "Make bigger." },
  { word: "inspect", definition: "Look at carefully." },
  { word: "invite", definition: "Ask someone to come." },
  { word: "itch", definition: "Feel like scratching." },
  { word: "jog", definition: "Run slowly." },
  { word: "join", definition: "Come together." },
  { word: "joke", definition: "Say something funny." },
  { word: "jump", definition: "Push your body into the air." },
  { word: "keep", definition: "Hold onto." },
  { word: "kick", definition: "Hit with your foot." },
  { word: "kiss", definition: "Touch with your lips to show love." },
  { word: "kneel", definition: "Go down on your knees." },
  { word: "knock", definition: "Hit a surface to make a sound." },
  { word: "know", definition: "Understand or remember." },
  { word: "land", definition: "Come down to the ground." },
  { word: "laugh", definition: "Make a happy sound." },
  { word: "lead", definition: "Go first and show the way." },
  { word: "lean", definition: "Rest against something." },
  { word: "learn", definition: "Gain knowledge." },
  { word: "leave", definition: "Go away." },
  { word: "lend", definition: "Let someone use something for a while." },
  { word: "lick", definition: "Touch with your tongue." },
  { word: "lift", definition: "Raise up." },
  { word: "light", definition: "Make bright or start a fire." },
  { word: "like", definition: "Enjoy." },
  { word: "listen", definition: "Pay attention to sound." },
  { word: "live", definition: "Be alive or stay somewhere." },
  { word: "load", definition: "Put things into something." },
  { word: "look", definition: "Use your eyes." },
  { word: "lose", definition: "Not have anymore." },
  { word: "love", definition: "Care about very much." },
  { word: "mail", definition: "Send through the post." },
  { word: "march", definition: "Walk with strong steps." },
  { word: "mark", definition: "Make a sign on something." },
  { word: "match", definition: "Go together or be the same." },
  { word: "matter", definition: "Be important." },
  { word: "mean", definition: "Have a certain meaning." },
  { word: "measure", definition: "Find the size of something." },
  { word: "melt", definition: "Become soft from heat." },
  { word: "mend", definition: "Fix." },
  { word: "mix", definition: "Stir things together." },
  { word: "moan", definition: "Make a low unhappy sound." },
  { word: "moo", definition: "Make the sound a cow makes." },
  { word: "move", definition: "Change place." },
  { word: "mow", definition: "Cut grass." },
  { word: "multiply", definition: "Make more by repeated adding." },
  { word: "murmur", definition: "Speak in a quiet voice." },
  { word: "name", definition: "Give a name." },
  { word: "nap", definition: "Sleep for a short time." },
  { word: "need", definition: "Must have." },
  { word: "nod", definition: "Move your head up and down." },
  { word: "notice", definition: "See or hear something." },
  { word: "obey", definition: "Do what you are told." },
  { word: "observe", definition: "Watch carefully." },
  { word: "open", definition: "Make not closed." },
  { word: "order", definition: "Ask for something to be brought." },
  { word: "pack", definition: "Put things into a bag or box." },
  { word: "paddle", definition: "Move through water with a paddle." },
  { word: "paint", definition: "Cover with color." },
  { word: "pass", definition: "Go by or hand over." },
  { word: "pat", definition: "Touch gently with your hand." },
  { word: "pause", definition: "Stop for a short time." },
  { word: "pay", definition: "Give money." },
  { word: "peel", definition: "Take the skin off." },
  { word: "peck", definition: "Hit lightly with a beak." },
  { word: "perform", definition: "Do in front of others." },
  { word: "pick", definition: "Choose or pull." },
  { word: "pile", definition: "Put in a heap." },
  { word: "pinch", definition: "Squeeze with fingers." },
  { word: "plan", definition: "Think ahead about what to do." },
  { word: "plant", definition: "Put in the ground so it can grow." },
  { word: "play", definition: "Have fun with a game or toy." },
  { word: "please", definition: "Make happy." },
  { word: "plug", definition: "Connect to power or fill a hole." },
  { word: "point", definition: "Show with your finger." },
  { word: "poke", definition: "Push gently with something pointed." },
  { word: "polish", definition: "Make smooth and shiny." },
  { word: "pop", definition: "Burst or make a quick sound." },
  { word: "pour", definition: "Let liquid flow out." },
  { word: "practice", definition: "Do again to get better." },
  { word: "pray", definition: "Talk to God." },
  { word: "prepare", definition: "Get ready." },
  { word: "press", definition: "Push down." },
  { word: "pretend", definition: "Act like something is true." },
  { word: "print", definition: "Make words or pictures on paper." },
  { word: "promise", definition: "Say you will do something." },
  { word: "protect", definition: "Keep safe." },
  { word: "pull", definition: "Draw toward you." },
  { word: "pump", definition: "Push air or liquid." },
  { word: "punch", definition: "Hit with a fist." },
  { word: "push", definition: "Shove away from you." },
  { word: "race", definition: "Move very fast to win." },
  { word: "reach", definition: "Stretch to touch." },
  { word: "read", definition: "Look at words and understand them." },
  { word: "relax", definition: "Rest and feel calm." },
  { word: "remember", definition: "Keep in your mind." },
  { word: "repair", definition: "Fix." },
  { word: "repeat", definition: "Say or do again." },
  { word: "reply", definition: "Answer back." },
  { word: "rest", definition: "Stop and relax." },
  { word: "return", definition: "Go back or give back." },
  { word: "rhyme", definition: "Have the same ending sound." },
  { word: "ride", definition: "Travel on something." },
  { word: "ring", definition: "Make a bell sound." },
  { word: "rinse", definition: "Wash lightly with water." },
  { word: "rise", definition: "Go up." },
  { word: "roast", definition: "Cook with dry heat." },
  { word: "roll", definition: "Move by turning over." },
  { word: "rub", definition: "Move back and forth against something." },
  { word: "row", definition: "Move a boat with oars." },
  { word: "ruin", definition: "Damage badly." },
  { word: "rule", definition: "Be in charge or make rules." },
  { word: "run", definition: "Move quickly on your feet." },
  { word: "rush", definition: "Move very fast." },
  { word: "sail", definition: "Travel on water in a boat." },
  { word: "save", definition: "Keep for later or protect." },
  { word: "say", definition: "Speak words." },
  { word: "scare", definition: "Make someone feel afraid." },
  { word: "scatter", definition: "Throw or spread in many directions." },
  { word: "scoop", definition: "Pick up with a curved tool." },
  { word: "scrub", definition: "Clean by rubbing hard." },
  { word: "search", definition: "Look for carefully." },
  { word: "see", definition: "Use your eyes." },
  { word: "seem", definition: "Appear to be." },
  { word: "select", definition: "Choose." },
  { word: "send", definition: "Make something go to someone." },
  { word: "serve", definition: "Give food or help." },
  { word: "settle", definition: "Come to rest or stay in a place." },
  { word: "sew", definition: "Join cloth with thread." },
  { word: "shake", definition: "Move back and forth." },
  { word: "share", definition: "Let others use or have some." },
  { word: "sharpen", definition: "Make an edge better for cutting." },
  { word: "shave", definition: "Cut hair close to the skin." },
  { word: "shine", definition: "Give off light." },
  { word: "shiver", definition: "Shake a little from cold or fear." },
  { word: "shop", definition: "Go buy things." },
  { word: "shout", definition: "Say very loudly." },
  { word: "show", definition: "Let someone see." },
  { word: "shrink", definition: "Become smaller." },
  { word: "shrug", definition: "Raise your shoulders." },
  { word: "sing", definition: "Make musical sounds with your voice." },
  { word: "sip", definition: "Drink a little." },
  { word: "sit", definition: "Rest on a chair or the ground." },
  { word: "skate", definition: "Move on skates." },
  { word: "skip", definition: "Hop or leave something out." },
  { word: "sleep", definition: "Rest with your eyes closed." },
  { word: "slide", definition: "Move smoothly along a surface." },
  { word: "slip", definition: "Slide by accident." },
  { word: "smell", definition: "Notice a scent." },
  { word: "smile", definition: "Show happiness with your face." },
  { word: "sneeze", definition: "Blow air out suddenly through your nose." },
  { word: "sniff", definition: "Smell quickly." },
  { word: "snore", definition: "Make a sleepy breathing sound." },
  { word: "soak", definition: "Make very wet." },
  { word: "solve", definition: "Find the answer." },
  { word: "sort", definition: "Put into groups." },
  { word: "sound", definition: "Seem to be." },
  { word: "speak", definition: "Talk." },
  { word: "spell", definition: "Say or write letters in order." },
  { word: "spend", definition: "Use time or money." },
  { word: "spill", definition: "Let something fall out by accident." },
  { word: "spin", definition: "Turn around quickly." },
  { word: "splash", definition: "Scatter water." },
  { word: "split", definition: "Break into parts." },
  { word: "spoil", definition: "Ruin or make less good." },
  { word: "spot", definition: "See or notice." },
  { word: "spray", definition: "Send out tiny drops." },
  { word: "spread", definition: "Open out over a larger space." },
  { word: "spring", definition: "Jump quickly." },
  { word: "stack", definition: "Put in a neat pile." },
  { word: "stamp", definition: "Press down hard or mark." },
  { word: "stare", definition: "Look for a long time." },
  { word: "start", definition: "Begin." },
  { word: "stay", definition: "Remain in a place." },
  { word: "steer", definition: "Guide the way something moves." },
  { word: "step", definition: "Move one foot forward." },
  { word: "stick", definition: "Stay attached." },
  { word: "stir", definition: "Mix with a spoon." },
  { word: "stop", definition: "End movement." },
  { word: "store", definition: "Keep for later." },
  { word: "stretch", definition: "Make longer or reach out." },
  { word: "strip", definition: "Remove a layer." },
  { word: "study", definition: "Learn carefully." },
  { word: "subtract", definition: "Take one number away from another." },
  { word: "suck", definition: "Pull in with your mouth." },
  { word: "suggest", definition: "Give an idea." },
  { word: "suit", definition: "Be right for." },
  { word: "supply", definition: "Provide what is needed." },
  { word: "support", definition: "Hold up or help." },
  { word: "surprise", definition: "Do something unexpected." },
  { word: "surround", definition: "Be all around." },
  { word: "swallow", definition: "Make food or drink go down." },
  { word: "swim", definition: "Move through water." },
  { word: "swing", definition: "Move back and forth." },
  { word: "talk", definition: "Speak." },
  { word: "taste", definition: "Notice flavor." },
  { word: "teach", definition: "Help someone learn." },
  { word: "tear", definition: "Rip." },
  { word: "tell", definition: "Give information." },
  { word: "thank", definition: "Show you are grateful." },
  { word: "think", definition: "Use your mind." },
  { word: "throw", definition: "Send through the air." },
  { word: "tickle", definition: "Touch lightly to make someone laugh." },
  { word: "tie", definition: "Fasten with a knot." },
  { word: "tip", definition: "Lean or pour a little." },
  { word: "toss", definition: "Throw lightly." },
  { word: "touch", definition: "Put your hand on." },
  { word: "trace", definition: "Follow a line or copy its shape." },
  { word: "trade", definition: "Exchange one thing for another." },
  { word: "train", definition: "Teach or practice for a skill." },
  { word: "travel", definition: "Go from place to place." },
  { word: "treat", definition: "Act toward someone in a certain way." },
  { word: "trim", definition: "Cut a little off." },
  { word: "trip", definition: "Stumble while walking." },
  { word: "trot", definition: "Run with short quick steps." },
  { word: "trust", definition: "Believe someone is honest and safe." },
  { word: "try", definition: "Make an effort." },
  { word: "tug", definition: "Pull with a quick strong motion." },
  { word: "tumble", definition: "Fall and roll." },
  { word: "turn", definition: "Move around to face another way." },
  { word: "twist", definition: "Turn into a new shape." },
  { word: "type", definition: "Write with a keyboard." },
  { word: "uncover", definition: "Take the cover off." },
  { word: "underline", definition: "Draw a line under words." },
  { word: "understand", definition: "Know what something means." },
  { word: "unfasten", definition: "Open something that was closed." },
  { word: "unpack", definition: "Take things out of a bag or box." },
  { word: "untie", definition: "Undo a knot." },
  { word: "update", definition: "Make more current." },
  { word: "use", definition: "Do something with." },
  { word: "vanish", definition: "Disappear." },
  { word: "visit", definition: "Go see a person or place." },
  { word: "vote", definition: "Choose by showing your opinion." },
  { word: "wait", definition: "Stay until something happens." },
  { word: "wake", definition: "Stop sleeping." },
  { word: "walk", definition: "Move on your feet." },
  { word: "wander", definition: "Walk without a set plan." },
  { word: "want", definition: "Wish to have." },
  { word: "warm", definition: "Make less cold." },
  { word: "warn", definition: "Tell about danger." },
  { word: "wash", definition: "Clean with water." },
  { word: "watch", definition: "Look at for a while." },
  { word: "wave", definition: "Move your hand side to side." },
  { word: "wear", definition: "Have clothes on your body." },
  { word: "weave", definition: "Make by crossing threads." },
  { word: "whisper", definition: "Speak very softly." },
  { word: "whistle", definition: "Make a tune with your lips." },
  { word: "wiggle", definition: "Move with small quick twists." },
  { word: "wink", definition: "Close one eye quickly." },
  { word: "wipe", definition: "Clean by rubbing." },
  { word: "wish", definition: "Hope for something." },
  { word: "wobble", definition: "Move in an unsteady way." },
  { word: "wonder", definition: "Think with curiosity." },
  { word: "work", definition: "Do a job or task." },
  { word: "worry", definition: "Feel nervous about something." },
  { word: "wrap", definition: "Cover around." },
  { word: "wrestle", definition: "Grapple and try to pin someone down." },
  { word: "write", definition: "Make letters or words." },
  { word: "yawn", definition: "Open your mouth wide when tired." },
  { word: "yell", definition: "Shout loudly." },
  { word: "zip", definition: "Close with a zipper." },
  { word: "zoom", definition: "Move very fast." }
];
