const WORD_BANK = [
  { word: "cat", definition: "A small pet that purrs and likes to chase things." },
  { word: "dog", definition: "A pet that barks and can be a good friend." },
  { word: "bird", definition: "An animal with feathers and wings." },
  { word: "fish", definition: "An animal that lives in water and swims." },
  { word: "cow", definition: "A farm animal that gives milk." },
  { word: "pig", definition: "A farm animal with a round body and curly tail." },
  { word: "horse", definition: "A large animal people can ride." },
  { word: "sheep", definition: "A farm animal with a thick wool coat." },
  { word: "goat", definition: "A farm animal that can climb and may have horns." },
  { word: "duck", definition: "A bird with a flat bill that likes water." },
  { word: "chicken", definition: "A farm bird that lays eggs." },
  { word: "rabbit", definition: "A small animal with long ears and a short tail." },
  { word: "mouse", definition: "A very small animal with a long tail." },
  { word: "bear", definition: "A large wild animal with fur and strong paws." },
  { word: "lion", definition: "A big wild cat known for its loud roar." },
  { word: "tiger", definition: "A big wild cat with dark stripes." },
  { word: "zebra", definition: "A horse-like animal with black-and-white stripes." },
  { word: "monkey", definition: "An animal that climbs and swings in trees." },
  { word: "elephant", definition: "A huge animal with a long trunk." },
  { word: "giraffe", definition: "A very tall animal with a long neck." },
  { word: "frog", definition: "A small animal that hops and lives near water." },
  { word: "snake", definition: "A long animal with no legs." },
  { word: "turtle", definition: "An animal with a hard shell on its back." },
  { word: "whale", definition: "A very large animal that lives in the ocean." },
  { word: "shark", definition: "A strong sea animal with sharp teeth." },
  { word: "dolphin", definition: "A smart sea animal that leaps from the water." },
  { word: "octopus", definition: "A sea animal with eight arms." },
  { word: "crab", definition: "A sea animal with claws and a hard shell." },
  { word: "bee", definition: "A flying insect that makes honey." },
  { word: "ant", definition: "A tiny insect that lives in busy groups." },
  { word: "butterfly", definition: "A colorful insect with large wings." },
  { word: "spider", definition: "A small creature with eight legs that spins webs." },
  { word: "worm", definition: "A long, soft animal with no legs." },
  { word: "owl", definition: "A bird that is often awake at night." },
  { word: "eagle", definition: "A large bird with strong wings and sharp sight." },
  { word: "hawk", definition: "A bird that hunts small animals from the sky." },
  { word: "fox", definition: "A wild animal with a bushy tail." },
  { word: "wolf", definition: "A wild animal that lives and hunts in groups." },
  { word: "deer", definition: "A gentle wild animal with long legs." },
  { word: "moose", definition: "A very large deer-like animal with big antlers." },
  { word: "goose", definition: "A water bird with a long neck." },
  { word: "swan", definition: "A large water bird known for its graceful neck." },
  { word: "turkey", definition: "A large bird with a fan-shaped tail." },
  { word: "donkey", definition: "A sturdy animal like a small horse." },
  { word: "camel", definition: "A desert animal with humps on its back." },
  { word: "panda", definition: "A black-and-white bear that eats bamboo." },
  { word: "koala", definition: "A tree-dwelling animal from Australia." },
  { word: "kangaroo", definition: "An Australian animal that hops and carries babies in a pouch." },
  { word: "leopard", definition: "A big wild cat with dark spots." },
  { word: "cheetah", definition: "A very fast big cat." },
  { word: "rhino", definition: "A huge animal with one or two horns on its nose." },
  { word: "hippo", definition: "A very large animal that spends much time in water." },
  { word: "otter", definition: "A playful animal that swims and floats in water." },
  { word: "seal", definition: "A smooth sea animal that rests on shore." },
  { word: "penguin", definition: "A black-and-white bird that cannot fly but swims well." },
  { word: "parrot", definition: "A bright bird that can copy sounds." },
  { word: "peacock", definition: "A bird with a large colorful tail." },
  { word: "flamingo", definition: "A tall pink bird with long legs." },
  { word: "lizard", definition: "A small scaly animal with four legs." },
  { word: "gecko", definition: "A tiny lizard that can climb walls." },
  { word: "iguana", definition: "A large lizard with a long tail." },
  { word: "alligator", definition: "A large reptile with a wide snout." },
  { word: "crocodile", definition: "A large reptile with strong jaws that lives near water." },
  { word: "bat", definition: "A flying animal that is awake at night." },
  { word: "squirrel", definition: "A small furry animal that climbs trees and gathers nuts." },
  { word: "chipmunk", definition: "A small striped animal with cheek pouches." },
  { word: "hamster", definition: "A small furry pet with tiny paws." },
  { word: "gerbil", definition: "A small pet animal with a long tail." },
  { word: "hedgehog", definition: "A small animal covered with sharp spines." },
  { word: "raccoon", definition: "A furry animal with a mask-like face." },
  { word: "skunk", definition: "A black-and-white animal known for a strong smell." },
  { word: "badger", definition: "A strong digging animal that lives underground." },
  { word: "beaver", definition: "An animal that builds dams in streams." },
  { word: "mole", definition: "A small animal that digs tunnels underground." },
  { word: "snail", definition: "A slow animal with a shell on its back." },
  { word: "slug", definition: "A soft, slow animal with no shell." },
  { word: "beetle", definition: "An insect with a hard outer covering." },
  { word: "ladybug", definition: "A tiny spotted beetle often seen in gardens." },
  { word: "grasshopper", definition: "An insect with long back legs for jumping." },
  { word: "dragonfly", definition: "A fast flying insect with long wings." },
  { word: "mosquito", definition: "A tiny flying insect that bites." },
  { word: "fly", definition: "A small flying insect found in many places." },
  { word: "moth", definition: "An insect like a butterfly that often flies at night." },
  { word: "shrimp", definition: "A small sea animal with a curved body." },
  { word: "lobster", definition: "A sea animal with claws and a hard shell." },
  { word: "clam", definition: "A shell animal that lives in sand or mud." },
  { word: "oyster", definition: "A shell animal that lives in water and can make pearls." },
  { word: "starfish", definition: "A sea animal shaped like a star." },
  { word: "seahorse", definition: "A tiny sea animal with a curled tail." },
  { word: "jellyfish", definition: "A soft sea animal with trailing arms." },
  { word: "apple", definition: "A round fruit that can be red, green, or yellow." },
  { word: "banana", definition: "A long yellow fruit with a peel." },
  { word: "orange", definition: "A juicy fruit with a thick skin." },
  { word: "grape", definition: "A small round fruit that grows in bunches." },
  { word: "pear", definition: "A sweet fruit that is narrow at the top and wide at the bottom." },
  { word: "peach", definition: "A soft fruit with fuzzy skin and a pit inside." },
  { word: "plum", definition: "A small smooth fruit with a pit." },
  { word: "cherry", definition: "A small round fruit with a pit and stem." },
  { word: "lemon", definition: "A sour yellow fruit." },
  { word: "lime", definition: "A small green fruit with a sour taste." },
  { word: "melon", definition: "A large fruit with lots of juicy flesh inside." },
  { word: "berry", definition: "A small juicy fruit." },
  { word: "mango", definition: "A sweet tropical fruit with a large pit." },
  { word: "pineapple", definition: "A tropical fruit with rough skin and a spiky top." },
  { word: "coconut", definition: "A hard tropical fruit with liquid and white flesh inside." },
  { word: "papaya", definition: "A soft tropical fruit with many black seeds." },
  { word: "kiwi", definition: "A small brown fruit with green flesh inside." },
  { word: "apricot", definition: "A small soft fruit with a pit." },
  { word: "carrot", definition: "A long orange root vegetable." },
  { word: "potato", definition: "A starchy vegetable that grows underground." },
  { word: "tomato", definition: "A soft red fruit often used like a vegetable." },
  { word: "corn", definition: "A yellow food that grows in rows on a cob." },
  { word: "pea", definition: "A small round green vegetable." },
  { word: "bean", definition: "A seed often eaten as food." },
  { word: "lettuce", definition: "A leafy green used in salads." },
  { word: "onion", definition: "A round vegetable with many layers inside." },
  { word: "garlic", definition: "A strong-smelling food made of cloves." },
  { word: "pepper", definition: "A vegetable that can be sweet or spicy." },
  { word: "broccoli", definition: "A green vegetable with a tree-like top." },
  { word: "cucumber", definition: "A long green vegetable with watery flesh." },
  { word: "pumpkin", definition: "A large orange squash used in fall." },
  { word: "squash", definition: "A vegetable with hard skin and soft inside." },
  { word: "cabbage", definition: "A leafy vegetable that grows in a round head." },
  { word: "celery", definition: "A crunchy green stalk often eaten raw." },
  { word: "spinach", definition: "A leafy green vegetable." },
  { word: "radish", definition: "A small root vegetable with a peppery taste." },
  { word: "beet", definition: "A round root vegetable that is often deep red." },
  { word: "turnip", definition: "A round root vegetable with white or purple skin." },
  { word: "mushroom", definition: "A soft fungus often used in cooking." },
  { word: "olive", definition: "A small fruit often used for oil or snacks." },
  { word: "avocado", definition: "A soft green fruit with a large pit." },
  { word: "bread", definition: "A baked food made from flour." },
  { word: "cake", definition: "A sweet baked treat for parties and desserts." },
  { word: "cookie", definition: "A small sweet baked treat." },
  { word: "pie", definition: "A baked dish with crust and filling." },
  { word: "pizza", definition: "A baked flat food with sauce and toppings." },
  { word: "sandwich", definition: "Food made by putting filling between bread." },
  { word: "soup", definition: "A warm food made with liquid." },
  { word: "salad", definition: "A mix of raw vegetables or other foods." },
  { word: "egg", definition: "A food with a shell that comes from birds." },
  { word: "cheese", definition: "A food made from milk." },
  { word: "milk", definition: "A white drink that comes from animals or plants." },
  { word: "juice", definition: "A drink made from fruit or vegetables." },
  { word: "water", definition: "A clear drink that people need to live." },
  { word: "pasta", definition: "Food made from dough and boiled in water." },
  { word: "noodle", definition: "A long thin piece of cooked dough." },
  { word: "rice", definition: "Small grains cooked and eaten as food." },
  { word: "cereal", definition: "A breakfast food often eaten with milk." },
  { word: "pancake", definition: "A flat round breakfast food cooked on a pan." },
  { word: "waffle", definition: "A breakfast food with square pockets." },
  { word: "muffin", definition: "A small baked bread or cake." },
  { word: "biscuit", definition: "A soft baked bread roll or a crisp treat, depending on where you live." },
  { word: "cracker", definition: "A thin crunchy snack." },
  { word: "yogurt", definition: "A creamy food made from milk." },
  { word: "butter", definition: "A soft yellow food spread made from cream." },
  { word: "jam", definition: "A sweet fruit spread." },
  { word: "jelly", definition: "A sweet spread made from fruit juice." },
  { word: "honey", definition: "A sweet sticky food made by bees." },
  { word: "syrup", definition: "A thick sweet liquid." },
  { word: "candy", definition: "A sweet treat made with sugar." },
  { word: "chocolate", definition: "A sweet treat made from cocoa." },
  { word: "popcorn", definition: "Corn that puffs up when heated." },
  { word: "pretzel", definition: "A baked snack twisted into a shape." },
  { word: "taco", definition: "A folded shell filled with food." },
  { word: "burrito", definition: "A rolled tortilla filled with food." },
  { word: "burger", definition: "A sandwich with a patty inside." },
  { word: "sausage", definition: "A tube-shaped food made from seasoned meat or other fillings." },
  { word: "bacon", definition: "Thin strips of salty meat." },
  { word: "meatball", definition: "A small round ball made from ground meat or another mix." },
  { word: "wafer", definition: "A thin crisp sweet snack." },
  { word: "fries", definition: "Thin pieces of potato cooked until crisp." },
  { word: "oatmeal", definition: "A warm breakfast made from oats." },
  { word: "pudding", definition: "A soft sweet dessert." },
  { word: "sundae", definition: "Ice cream served with toppings." },
  { word: "cupcake", definition: "A small cake baked in a paper cup." },
  { word: "donut", definition: "A sweet fried or baked ring-shaped treat." },
  { word: "chair", definition: "A seat for one person." },
  { word: "table", definition: "A flat piece of furniture with legs." },
  { word: "desk", definition: "A table used for work or school." },
  { word: "bed", definition: "Furniture used for sleeping." },
  { word: "pillow", definition: "A soft cushion for your head." },
  { word: "blanket", definition: "A warm cover used on a bed." },
  { word: "couch", definition: "A soft seat for more than one person." },
  { word: "lamp", definition: "Something that gives light." },
  { word: "clock", definition: "Something that shows time." },
  { word: "mirror", definition: "A smooth surface that shows your reflection." },
  { word: "door", definition: "A panel that opens and closes an entrance." },
  { word: "window", definition: "An opening with glass that lets in light." },
  { word: "wall", definition: "The side part of a room or building." },
  { word: "floor", definition: "The bottom surface you walk on." },
  { word: "roof", definition: "The top covering of a building." },
  { word: "house", definition: "A building where people live." },
  { word: "home", definition: "The place where someone lives and feels they belong." },
  { word: "room", definition: "A space inside a building." },
  { word: "kitchen", definition: "A room where food is made." },
  { word: "bathroom", definition: "A room with a sink, toilet, or shower." },
  { word: "bedroom", definition: "A room for sleeping." },
  { word: "garage", definition: "A place where cars or tools are kept." },
  { word: "garden", definition: "A place where plants or flowers are grown." },
  { word: "fence", definition: "A barrier around a yard or area." },
  { word: "bucket", definition: "A container with a handle." },
  { word: "basket", definition: "A container used to carry things." },
  { word: "bottle", definition: "A container for liquids." },
  { word: "cup", definition: "A small container used for drinking." },
  { word: "plate", definition: "A flat dish for food." },
  { word: "bowl", definition: "A round dish with deep sides." },
  { word: "spoon", definition: "A tool for eating or stirring with a round end." },
  { word: "fork", definition: "A tool for eating with pointed ends." },
  { word: "knife", definition: "A tool with a blade for cutting." },
  { word: "napkin", definition: "A piece of cloth or paper used while eating." },
  { word: "towel", definition: "A cloth used for drying." },
  { word: "soap", definition: "Something used for washing." },
  { word: "brush", definition: "A tool with bristles for cleaning or styling." },
  { word: "comb", definition: "A tool with teeth for fixing hair." },
  { word: "toothbrush", definition: "A small brush used to clean teeth." },
  { word: "backpack", definition: "A bag carried on your back." },
  { word: "pencil", definition: "A tool used for writing that can be erased." },
  { word: "pen", definition: "A writing tool that uses ink." },
  { word: "crayon", definition: "A colored stick used for drawing." },
  { word: "marker", definition: "A pen-like tool with strong color." },
  { word: "eraser", definition: "Something used to rub out pencil marks." },
  { word: "ruler", definition: "A straight tool used for measuring." },
  { word: "notebook", definition: "Pages bound together for writing." },
  { word: "paper", definition: "Thin material used for writing or drawing." },
  { word: "book", definition: "Pages with words or pictures bound together." },
  { word: "story", definition: "A tale with characters and events." },
  { word: "map", definition: "A drawing that shows where places are." },
  { word: "globe", definition: "A round model of Earth." },
  { word: "toy", definition: "Something made for play." },
  { word: "game", definition: "An activity with rules for fun." },
  { word: "puzzle", definition: "A problem or toy you solve by thinking." },
  { word: "block", definition: "A solid piece used for building or stacking." },
  { word: "ball", definition: "A round object used in play and sports." },
  { word: "kite", definition: "Something that flies in the wind on a string." },
  { word: "rope", definition: "A thick cord used for tying or pulling." },
  { word: "string", definition: "A thin cord." },
  { word: "tape", definition: "A sticky strip used to hold things together." },
  { word: "glue", definition: "A sticky substance used to join things." },
  { word: "scissors", definition: "A tool with two blades for cutting." },
  { word: "hammer", definition: "A tool used for pounding nails." },
  { word: "nail", definition: "A small metal pin used in building." },
  { word: "screw", definition: "A metal fastener with a spiral shape." },
  { word: "wrench", definition: "A tool used to tighten or loosen nuts and bolts." },
  { word: "shovel", definition: "A tool used for digging." },
  { word: "rake", definition: "A tool used to gather leaves or smooth soil." },
  { word: "broom", definition: "A tool used for sweeping." },
  { word: "mop", definition: "A tool used for washing floors." },
  { word: "vacuum", definition: "A machine that cleans by sucking up dirt." },
  { word: "phone", definition: "A device used to call or message people." },
  { word: "camera", definition: "A device used to take pictures." },
  { word: "radio", definition: "A device that plays broadcasts and music." },
  { word: "speaker", definition: "Something that plays sound out loud." },
  { word: "screen", definition: "A flat surface that shows pictures or words." },
  { word: "keyboard", definition: "A set of keys used to type." },
  { word: "remote", definition: "A small device used to control something from far away." },
  { word: "battery", definition: "A small power source for devices." },
  { word: "charger", definition: "Something that gives power to a device again." },
  { word: "helmet", definition: "Hard gear worn to protect the head." },
  { word: "umbrella", definition: "Something that opens to keep off rain." },
  { word: "wallet", definition: "A small holder for money and cards." },
  { word: "pocket", definition: "A small cloth space in clothing used to hold things." },
  { word: "zipper", definition: "A fastener with two rows that slide together." },
  { word: "button", definition: "A small fastener on clothing or a part you press." },
  { word: "key", definition: "A tool used to open a lock." },
  { word: "lock", definition: "Something that keeps a door, box, or gate closed." },
  { word: "chain", definition: "Linked metal rings joined together." },
  { word: "bag", definition: "A soft container used to carry things." },
  { word: "box", definition: "A container with sides and a lid or opening." },
  { word: "gift", definition: "Something given to another person." },
  { word: "coin", definition: "A piece of metal money." },
  { word: "school", definition: "A place where children go to learn." },
  { word: "classroom", definition: "A room where lessons happen." },
  { word: "library", definition: "A place with many books to read or borrow." },
  { word: "park", definition: "An outdoor place for play or rest." },
  { word: "playground", definition: "An outdoor area with equipment for children to play on." },
  { word: "store", definition: "A place where things are sold." },
  { word: "market", definition: "A place where many goods or foods are sold." },
  { word: "bakery", definition: "A place where bread and sweet treats are made or sold." },
  { word: "farm", definition: "A place where crops are grown and animals are kept." },
  { word: "zoo", definition: "A place where people can see animals." },
  { word: "beach", definition: "Sandy or rocky land beside water." },
  { word: "river", definition: "A long moving stream of water." },
  { word: "lake", definition: "A large area of water surrounded by land." },
  { word: "pond", definition: "A small still body of water." },
  { word: "stream", definition: "A small flowing body of water." },
  { word: "ocean", definition: "A huge body of salt water." },
  { word: "island", definition: "Land with water all around it." },
  { word: "forest", definition: "A large area filled with trees." },
  { word: "jungle", definition: "A thick hot forest with many plants." },
  { word: "desert", definition: "A very dry land with little rain." },
  { word: "mountain", definition: "Very high land that rises above the ground around it." },
  { word: "hill", definition: "A raised area of land smaller than a mountain." },
  { word: "valley", definition: "Low land between hills or mountains." },
  { word: "cave", definition: "A hollow place inside rock or earth." },
  { word: "cliff", definition: "A very steep rock face." },
  { word: "waterfall", definition: "Water falling from a high place." },
  { word: "tree", definition: "A tall plant with a trunk and branches." },
  { word: "bush", definition: "A low plant with many branches." },
  { word: "flower", definition: "The colorful part of a plant." },
  { word: "grass", definition: "Short green plants that cover the ground." },
  { word: "leaf", definition: "The flat green part of many plants." },
  { word: "root", definition: "The part of a plant that grows underground." },
  { word: "branch", definition: "A part that grows out from a tree trunk." },
  { word: "seed", definition: "The small part of a plant that can grow into a new one." },
  { word: "rock", definition: "A hard piece of stone." },
  { word: "stone", definition: "Hard natural material from the ground." },
  { word: "cloud", definition: "A white or gray shape in the sky made of tiny drops of water." },
  { word: "rain", definition: "Water that falls from clouds." },
  { word: "snow", definition: "Soft white ice crystals that fall from the sky." },
  { word: "wind", definition: "Moving air." },
  { word: "storm", definition: "Weather with strong wind, rain, or thunder." },
  { word: "thunder", definition: "The loud sound heard during a storm." },
  { word: "lightning", definition: "A bright flash in the sky during a storm." },
  { word: "rainbow", definition: "A band of colors seen in the sky after rain." },
  { word: "sun", definition: "The star that gives Earth light and warmth." },
  { word: "moon", definition: "The round object that moves around Earth at night." },
  { word: "star", definition: "A bright point of light in the night sky." },
  { word: "planet", definition: "A large round world in space." },
  { word: "space", definition: "The huge area beyond Earth." },
  { word: "road", definition: "A path for cars and other vehicles." },
  { word: "street", definition: "A road in a town or city." },
  { word: "bridge", definition: "A structure that goes over water or land to connect places." },
  { word: "tunnel", definition: "A passage that goes through or under something." },
  { word: "path", definition: "A way for walking." },
  { word: "trail", definition: "A path through woods, hills, or other nature." },
  { word: "sidewalk", definition: "The safe walkway beside a street." },
  { word: "town", definition: "A place where people live that is smaller than a city." },
  { word: "city", definition: "A large place where many people live and work." },
  { word: "village", definition: "A very small town." },
  { word: "country", definition: "A large land area that is its own nation." },
  { word: "airport", definition: "A place where airplanes take off and land." },
  { word: "station", definition: "A place where buses or trains stop." },
  { word: "harbor", definition: "A sheltered place where boats stay." },
  { word: "port", definition: "A place where ships load, unload, or stop." },
  { word: "camp", definition: "A place where people stay outdoors for a short time." },
  { word: "tent", definition: "A fabric shelter used outdoors." },
  { word: "castle", definition: "A large strong building where royalty once lived." },
  { word: "tower", definition: "A very tall building or part of one." },
  { word: "museum", definition: "A place where important objects are shown." },
  { word: "hospital", definition: "A place where sick or hurt people get care." },
  { word: "office", definition: "A place where people do work at desks." },
  { word: "church", definition: "A building where Christians gather to worship." },
  { word: "temple", definition: "A building used for worship in some religions." },
  { word: "theater", definition: "A place where plays or movies are shown." },
  { word: "stadium", definition: "A large place where sports or big events happen." },
  { word: "restaurant", definition: "A place where meals are made and served." },
  { word: "add", definition: "Put more in." },
  { word: "agree", definition: "Say yes to an idea." },
  { word: "allow", definition: "Let something happen." },
  { word: "answer", definition: "Say or write a reply." },
  { word: "arrive", definition: "Get to a place." },
  { word: "ask", definition: "Say you want to know something." },
  { word: "bake", definition: "Cook in an oven." },
  { word: "balance", definition: "Stay steady without falling." },
  { word: "bark", definition: "Make a dog sound." },
  { word: "bathe", definition: "Wash in water." },
  { word: "beam", definition: "Smile brightly." },
  { word: "beg", definition: "Ask strongly for something." },
  { word: "behave", definition: "Act in a good way." },
  { word: "blink", definition: "Open and close your eyes quickly." },
  { word: "bloom", definition: "Open into flowers." },
  { word: "blow", definition: "Push air." },
  { word: "blush", definition: "Turn pink from feeling shy." },
  { word: "boil", definition: "Heat until bubbling." },
  { word: "borrow", definition: "Take something to use and give back later." },
  { word: "bounce", definition: "Spring up after hitting a surface." },
  { word: "bow", definition: "Bend forward." },
  { word: "break", definition: "Make something come apart." },
  { word: "breathe", definition: "Take air in and out." },
  { word: "bring", definition: "Carry something to a place." },
  { word: "build", definition: "Make something." },
  { word: "bump", definition: "Hit lightly." },
  { word: "burn", definition: "Be on fire or hurt from heat." },
  { word: "bury", definition: "Put under the ground." },
  { word: "buy", definition: "Pay money for something." },
  { word: "call", definition: "Say or shout to someone." },
  { word: "care", definition: "Look after someone or something." },
  { word: "carry", definition: "Hold and move something." },
  { word: "carve", definition: "Cut into a shape." },
  { word: "catch", definition: "Grab something moving." },
  { word: "chase", definition: "Run after." },
  { word: "chat", definition: "Talk in a friendly way." },
  { word: "chew", definition: "Bite food again and again." },
  { word: "clap", definition: "Hit your hands together." },
  { word: "clean", definition: "Make tidy." },
  { word: "climb", definition: "Go up." },
  { word: "close", definition: "Shut." },
  { word: "coach", definition: "Teach and guide." },
  { word: "collect", definition: "Gather things together." },
  { word: "color", definition: "Add color to something." },
  { word: "compare", definition: "Look at how things are alike or different." },
  { word: "complain", definition: "Say you are not happy." },
  { word: "complete", definition: "Finish." },
  { word: "cook", definition: "Make food with heat." },
  { word: "cool", definition: "Make less warm." },
  { word: "copy", definition: "Make one like another." },
  { word: "count", definition: "Say numbers in order." },
  { word: "cover", definition: "Put something over the top." },
  { word: "crawl", definition: "Move low to the ground." },
  { word: "cross", definition: "Go from one side to another." },
  { word: "cry", definition: "Make tears." },
  { word: "dance", definition: "Move to music." },
  { word: "dare", definition: "Be brave enough to do something." },
  { word: "decide", definition: "Choose." },
  { word: "decorate", definition: "Make something look nicer." },
  { word: "deliver", definition: "Bring something to a place." },
  { word: "depend", definition: "Need someone or something." },
  { word: "describe", definition: "Tell what something is like." },
  { word: "design", definition: "Plan how something will look or work." },
  { word: "dig", definition: "Move dirt with your hands or a tool." },
  { word: "disagree", definition: "Say no to an idea." },
  { word: "discover", definition: "Find something new." },
  { word: "dive", definition: "Jump into water." },
  { word: "do", definition: "Perform an action." },
  { word: "draw", definition: "Make a picture." },
  { word: "dream", definition: "See pictures in your mind while sleeping." },
  { word: "dress", definition: "Put clothes on." },
  { word: "drink", definition: "Swallow a liquid." },
  { word: "drip", definition: "Fall in small drops." },
  { word: "drop", definition: "Let something fall." },
  { word: "dry", definition: "Make not wet." },
  { word: "dust", definition: "Clean away fine dirt." },
  { word: "eat", definition: "Put food in your mouth and swallow it." },
  { word: "echo", definition: "Repeat a sound." },
  { word: "end", definition: "Stop." },
  { word: "enjoy", definition: "Like something." },
  { word: "enter", definition: "Go in." },
  { word: "escape", definition: "Get away." },
  { word: "exercise", definition: "Move your body to get stronger." },
  { word: "explain", definition: "Make something easy to understand." },
  { word: "explore", definition: "Look around and discover." },
  { word: "face", definition: "Look toward." },
  { word: "fade", definition: "Slowly lose color or strength." },
  { word: "fail", definition: "Not succeed." },
  { word: "fall", definition: "Drop down." },
  { word: "fasten", definition: "Close or attach tightly." },
  { word: "feed", definition: "Give food to." },
  { word: "feel", definition: "Sense something." },
  { word: "fetch", definition: "Go get something." },
  { word: "fight", definition: "Try to hurt or beat." },
  { word: "fill", definition: "Make full." },
  { word: "find", definition: "Discover where something is." },
  { word: "finish", definition: "Complete." },
  { word: "fit", definition: "Be the right size." },
  { word: "fix", definition: "Make work again." },
  { word: "flap", definition: "Move up and down quickly." },
  { word: "float", definition: "Stay on top of water or in the air." },
  { word: "flood", definition: "Cover with lots of water." },
  { word: "flow", definition: "Move smoothly." },
  { word: "fly", definition: "Move through the air." },
  { word: "fold", definition: "Bend over." },
  { word: "follow", definition: "Go after." },
  { word: "fool", definition: "Trick someone." },
  { word: "force", definition: "Make something happen." },
  { word: "form", definition: "Make or shape." },
  { word: "found", definition: "Start and build something new." },
  { word: "freeze", definition: "Turn very cold and hard." },
  { word: "fry", definition: "Cook in hot oil." },
  { word: "gather", definition: "Bring together." },
  { word: "gaze", definition: "Look for a while." },
  { word: "get", definition: "Receive or reach." },
  { word: "giggle", definition: "Laugh in a light way." },
  { word: "give", definition: "Hand something to someone." },
  { word: "glance", definition: "Look quickly." },
  { word: "glow", definition: "Shine softly." },
  { word: "grab", definition: "Take quickly." },
  { word: "grin", definition: "Smile widely." },
  { word: "grip", definition: "Hold tightly." },
  { word: "groan", definition: "Make a low unhappy sound." },
  { word: "grow", definition: "Become bigger." },
  { word: "guess", definition: "Answer without knowing for sure." },
  { word: "guide", definition: "Lead the way." },
  { word: "hand", definition: "Give by using your hand." },
  { word: "hang", definition: "Be held from above." },
  { word: "happen", definition: "Take place." },
  { word: "hatch", definition: "Come out of an egg." },
  { word: "hate", definition: "Strongly dislike." },
  { word: "have", definition: "Own or hold." },
  { word: "head", definition: "Go toward a place." },
  { word: "heal", definition: "Get better." },
  { word: "hear", definition: "Notice sound." },
  { word: "help", definition: "Make something easier." },
  { word: "hide", definition: "Keep out of sight." },
  { word: "hike", definition: "Take a long walk outdoors." },
  { word: "hop", definition: "Jump in little steps." },
  { word: "hope", definition: "Want something good to happen." },
  { word: "hug", definition: "Hold someone close." },
  { word: "hum", definition: "Make a soft singing sound." },
  { word: "hunt", definition: "Look for." },
  { word: "hurry", definition: "Move fast." },
  { word: "imagine", definition: "Picture something in your mind." },
  { word: "improve", definition: "Make better." },
  { word: "include", definition: "Have as part of it." },
  { word: "increase", definition: "Make bigger." },
  { word: "inspect", definition: "Look at carefully." },
  { word: "invite", definition: "Ask someone to come." },
  { word: "itch", definition: "Feel like scratching." },
  { word: "jog", definition: "Run slowly." },
  { word: "join", definition: "Come together." },
  { word: "joke", definition: "Say something funny." },
  { word: "jump", definition: "Push your body into the air." },
  { word: "keep", definition: "Hold onto." },
  { word: "kick", definition: "Hit with your foot." },
  { word: "kiss", definition: "Touch with your lips to show love." },
  { word: "kneel", definition: "Go down on your knees." },
  { word: "knock", definition: "Hit a surface to make a sound." },
  { word: "know", definition: "Understand or remember." },
  { word: "land", definition: "Come down to the ground." },
  { word: "laugh", definition: "Make a happy sound." },
  { word: "lead", definition: "Go first and show the way." },
  { word: "lean", definition: "Rest against something." },
  { word: "learn", definition: "Gain knowledge." },
  { word: "leave", definition: "Go away." },
  { word: "lend", definition: "Let someone use something for a while." },
  { word: "lick", definition: "Touch with your tongue." },
  { word: "lift", definition: "Raise up." },
  { word: "light", definition: "Make bright or start a fire." },
  { word: "like", definition: "Enjoy." },
  { word: "listen", definition: "Pay attention to sound." },
  { word: "live", definition: "Be alive or stay somewhere." },
  { word: "load", definition: "Put things into something." },
  { word: "look", definition: "Use your eyes." },
  { word: "lose", definition: "Not have anymore." },
  { word: "love", definition: "Care about very much." },
  { word: "mail", definition: "Send through the post." },
  { word: "march", definition: "Walk with strong steps." },
  { word: "mark", definition: "Make a sign on something." },
  { word: "match", definition: "Go together or be the same." },
  { word: "matter", definition: "Be important." },
  { word: "mean", definition: "Have a certain meaning." },
  { word: "measure", definition: "Find the size of something." },
  { word: "melt", definition: "Become soft from heat." },
  { word: "mend", definition: "Fix." },
  { word: "mix", definition: "Stir things together." },
  { word: "moan", definition: "Make a low unhappy sound." },
  { word: "moo", definition: "Make the sound a cow makes." },
  { word: "move", definition: "Change place." },
  { word: "mow", definition: "Cut grass." },
  { word: "multiply", definition: "Make more by repeated adding." },
  { word: "murmur", definition: "Speak in a quiet voice." },
  { word: "name", definition: "Give a name." },
  { word: "nap", definition: "Sleep for a short time." },
  { word: "need", definition: "Must have." },
  { word: "nod", definition: "Move your head up and down." },
  { word: "notice", definition: "See or hear something." },
  { word: "obey", definition: "Do what you are told." },
  { word: "observe", definition: "Watch carefully." },
  { word: "open", definition: "Make not closed." },
  { word: "order", definition: "Ask for something to be brought." },
  { word: "pack", definition: "Put things into a bag or box." },
  { word: "paddle", definition: "Move through water with a paddle." },
  { word: "paint", definition: "Cover with color." },
  { word: "pass", definition: "Go by or hand over." },
  { word: "pat", definition: "Touch gently with your hand." },
  { word: "pause", definition: "Stop for a short time." },
  { word: "pay", definition: "Give money." },
  { word: "peel", definition: "Take the skin off." },
  { word: "peck", definition: "Hit lightly with a beak." },
  { word: "perform", definition: "Do in front of others." },
  { word: "pick", definition: "Choose or pull." },
  { word: "pile", definition: "Put in a heap." },
  { word: "pinch", definition: "Squeeze with fingers." },
  { word: "plan", definition: "Think ahead about what to do." },
  { word: "plant", definition: "Put in the ground so it can grow." },
  { word: "play", definition: "Have fun with a game or toy." },
  { word: "please", definition: "Make happy." },
  { word: "plug", definition: "Connect to power or fill a hole." },
  { word: "point", definition: "Show with your finger." },
  { word: "poke", definition: "Push gently with something pointed." },
  { word: "polish", definition: "Make smooth and shiny." },
  { word: "pop", definition: "Burst or make a quick sound." },
  { word: "pour", definition: "Let liquid flow out." },
  { word: "practice", definition: "Do again to get better." },
  { word: "pray", definition: "Talk to God." },
  { word: "prepare", definition: "Get ready." },
  { word: "press", definition: "Push down." },
  { word: "pretend", definition: "Act like something is true." },
  { word: "print", definition: "Make words or pictures on paper." },
  { word: "promise", definition: "Say you will do something." },
  { word: "protect", definition: "Keep safe." },
  { word: "pull", definition: "Draw toward you." },
  { word: "pump", definition: "Push air or liquid." },
  { word: "punch", definition: "Hit with a fist." },
  { word: "push", definition: "Shove away from you." },
  { word: "race", definition: "Move very fast to win." },
  { word: "reach", definition: "Stretch to touch." },
  { word: "read", definition: "Look at words and understand them." },
  { word: "relax", definition: "Rest and feel calm." },
  { word: "remember", definition: "Keep in your mind." },
  { word: "repair", definition: "Fix." },
  { word: "repeat", definition: "Say or do again." },
  { word: "reply", definition: "Answer back." },
  { word: "rest", definition: "Stop and relax." },
  { word: "return", definition: "Go back or give back." },
  { word: "rhyme", definition: "Have the same ending sound." },
  { word: "ride", definition: "Travel on something." },
  { word: "ring", definition: "Make a bell sound." },
  { word: "rinse", definition: "Wash lightly with water." },
  { word: "rise", definition: "Go up." },
  { word: "roast", definition: "Cook with dry heat." },
  { word: "roll", definition: "Move by turning over." },
  { word: "rub", definition: "Move back and forth against something." },
  { word: "row", definition: "Move a boat with oars." },
  { word: "ruin", definition: "Damage badly." },
  { word: "rule", definition: "Be in charge or make rules." },
  { word: "run", definition: "Move quickly on your feet." },
  { word: "rush", definition: "Move very fast." },
  { word: "sail", definition: "Travel on water in a boat." },
  { word: "save", definition: "Keep for later or protect." },
  { word: "say", definition: "Speak words." },
  { word: "scare", definition: "Make someone feel afraid." },
  { word: "scatter", definition: "Throw or spread in many directions." },
  { word: "scoop", definition: "Pick up with a curved tool." },
  { word: "scrub", definition: "Clean by rubbing hard." },
  { word: "search", definition: "Look for carefully." },
  { word: "see", definition: "Use your eyes." },
  { word: "seem", definition: "Appear to be." },
  { word: "select", definition: "Choose." },
  { word: "send", definition: "Make something go to someone." },
  { word: "serve", definition: "Give food or help." },
  { word: "settle", definition: "Come to rest or stay in a place." },
  { word: "sew", definition: "Join cloth with thread." },
  { word: "shake", definition: "Move back and forth." },
  { word: "share", definition: "Let others use or have some." },
  { word: "sharpen", definition: "Make an edge better for cutting." },
  { word: "shave", definition: "Cut hair close to the skin." },
  { word: "shine", definition: "Give off light." },
  { word: "shiver", definition: "Shake a little from cold or fear." },
  { word: "shop", definition: "Go buy things." },
  { word: "shout", definition: "Say very loudly." },
  { word: "show", definition: "Let someone see." },
  { word: "shrink", definition: "Become smaller." },
  { word: "shrug", definition: "Raise your shoulders." },
  { word: "sing", definition: "Make musical sounds with your voice." },
  { word: "sip", definition: "Drink a little." },
  { word: "sit", definition: "Rest on a chair or the ground." },
  { word: "skate", definition: "Move on skates." },
  { word: "skip", definition: "Hop or leave something out." },
  { word: "sleep", definition: "Rest with your eyes closed." },
  { word: "slide", definition: "Move smoothly along a surface." },
  { word: "slip", definition: "Slide by accident." },
  { word: "smell", definition: "Notice a scent." },
  { word: "smile", definition: "Show happiness with your face." },
  { word: "sneeze", definition: "Blow air out suddenly through your nose." },
  { word: "sniff", definition: "Smell quickly." },
  { word: "snore", definition: "Make a sleepy breathing sound." },
  { word: "soak", definition: "Make very wet." },
  { word: "solve", definition: "Find the answer." },
  { word: "sort", definition: "Put into groups." },
  { word: "sound", definition: "Seem to be." },
  { word: "speak", definition: "Talk." },
  { word: "spell", definition: "Say or write letters in order." },
  { word: "spend", definition: "Use time or money." },
  { word: "spill", definition: "Let something fall out by accident." },
  { word: "spin", definition: "Turn around quickly." },
  { word: "splash", definition: "Scatter water." },
  { word: "split", definition: "Break into parts." },
  { word: "spoil", definition: "Ruin or make less good." },
  { word: "spot", definition: "See or notice." },
  { word: "spray", definition: "Send out tiny drops." },
  { word: "spread", definition: "Open out over a larger space." },
  { word: "spring", definition: "Jump quickly." },
  { word: "stack", definition: "Put in a neat pile." },
  { word: "stamp", definition: "Press down hard or mark." },
  { word: "stare", definition: "Look for a long time." },
  { word: "start", definition: "Begin." },
  { word: "stay", definition: "Remain in a place." },
  { word: "steer", definition: "Guide the way something moves." },
  { word: "step", definition: "Move one foot forward." },
  { word: "stick", definition: "Stay attached." },
  { word: "stir", definition: "Mix with a spoon." },
  { word: "stop", definition: "End movement." },
  { word: "store", definition: "Keep for later." },
  { word: "stretch", definition: "Make longer or reach out." },
  { word: "strip", definition: "Remove a layer." },
  { word: "study", definition: "Learn carefully." },
  { word: "subtract", definition: "Take one number away from another." },
  { word: "suck", definition: "Pull in with your mouth." },
  { word: "suggest", definition: "Give an idea." },
  { word: "suit", definition: "Be right for." },
  { word: "supply", definition: "Provide what is needed." },
  { word: "support", definition: "Hold up or help." },
  { word: "surprise", definition: "Do something unexpected." },
  { word: "surround", definition: "Be all around." },
  { word: "swallow", definition: "Make food or drink go down." },
  { word: "swim", definition: "Move through water." },
  { word: "swing", definition: "Move back and forth." },
  { word: "talk", definition: "Speak." },
  { word: "taste", definition: "Notice flavor." },
  { word: "teach", definition: "Help someone learn." },
  { word: "tear", definition: "Rip." },
  { word: "tell", definition: "Give information." },
  { word: "thank", definition: "Show you are grateful." },
  { word: "think", definition: "Use your mind." },
  { word: "throw", definition: "Send through the air." },
  { word: "tickle", definition: "Touch lightly to make someone laugh." },
  { word: "tie", definition: "Fasten with a knot." },
  { word: "tip", definition: "Lean or pour a little." },
  { word: "toss", definition: "Throw lightly." },
  { word: "touch", definition: "Put your hand on." },
  { word: "trace", definition: "Follow a line or copy its shape." },
  { word: "trade", definition: "Exchange one thing for another." },
  { word: "train", definition: "Teach or practice for a skill." },
  { word: "travel", definition: "Go from place to place." },
  { word: "treat", definition: "Act toward someone in a certain way." },
  { word: "trim", definition: "Cut a little off." },
  { word: "trip", definition: "Stumble while walking." },
  { word: "trot", definition: "Run with short quick steps." },
  { word: "trust", definition: "Believe someone is honest and safe." },
  { word: "try", definition: "Make an effort." },
  { word: "tug", definition: "Pull with a quick strong motion." },
  { word: "tumble", definition: "Fall and roll." },
  { word: "turn", definition: "Move around to face another way." },
  { word: "twist", definition: "Turn into a new shape." },
  { word: "type", definition: "Write with a keyboard." },
  { word: "uncover", definition: "Take the cover off." },
  { word: "underline", definition: "Draw a line under words." },
  { word: "understand", definition: "Know what something means." },
  { word: "unfasten", definition: "Open something that was closed." },
  { word: "unpack", definition: "Take things out of a bag or box." },
  { word: "untie", definition: "Undo a knot." },
  { word: "update", definition: "Make more current." },
  { word: "use", definition: "Do something with." },
  { word: "vanish", definition: "Disappear." },
  { word: "visit", definition: "Go see a person or place." },
  { word: "vote", definition: "Choose by showing your opinion." },
  { word: "wait", definition: "Stay until something happens." },
  { word: "wake", definition: "Stop sleeping." },
  { word: "walk", definition: "Move on your feet." },
  { word: "wander", definition: "Walk without a set plan." },
  { word: "want", definition: "Wish to have." },
  { word: "warm", definition: "Make less cold." },
  { word: "warn", definition: "Tell about danger." },
  { word: "wash", definition: "Clean with water." },
  { word: "watch", definition: "Look at for a while." },
  { word: "wave", definition: "Move your hand side to side." },
  { word: "wear", definition: "Have clothes on your body." },
  { word: "weave", definition: "Make by crossing threads." },
  { word: "whisper", definition: "Speak very softly." },
  { word: "whistle", definition: "Make a tune with your lips." },
  { word: "wiggle", definition: "Move with small quick twists." },
  { word: "wink", definition: "Close one eye quickly." },
  { word: "wipe", definition: "Clean by rubbing." },
  { word: "wish", definition: "Hope for something." },
  { word: "wobble", definition: "Move in an unsteady way." },
  { word: "wonder", definition: "Think with curiosity." },
  { word: "work", definition: "Do a job or task." },
  { word: "worry", definition: "Feel nervous about something." },
  { word: "wrap", definition: "Cover around." },
  { word: "wrestle", definition: "Grapple and try to pin someone down." },
  { word: "write", definition: "Make letters or words." },
  { word: "yawn", definition: "Open your mouth wide when tired." },
  { word: "yell", definition: "Shout loudly." },
  { word: "zip", definition: "Close with a zipper." },
  { word: "zoom", definition: "Move very fast." },
  { word: "laptop", definition: "A portable computer that opens and closes." },
  { word: "computer", definition: "An electronic machine that can store, show, and use information." },
  { word: "device", definition: "A tool or machine made for a special job." },
  { word: "tablet", definition: "A flat handheld screen used for apps, games, and reading." },
  { word: "monitor", definition: "A screen that shows pictures, video, or words from a machine." },
  { word: "printer", definition: "A machine that puts words or pictures onto paper." },
  { word: "internet", definition: "A huge network that connects computers around the world." },
  { word: "website", definition: "A group of pages you can visit online." },
  { word: "robot", definition: "A machine that can do tasks by following instructions." },
  { word: "drone", definition: "A small flying machine controlled from far away or by a program." },
  { word: "engine", definition: "A machine that makes power to move something." },
  { word: "gear", definition: "A toothed wheel that helps parts turn together." },
  { word: "cable", definition: "A thick wire used to carry power or signals." },
  { word: "signal", definition: "A sign, sound, or message that gives information." },
  { word: "pixel", definition: "A tiny dot that helps make a picture on a screen." },
  { word: "cursor", definition: "A small moving mark that shows where you are on a screen." },
  { word: "folder", definition: "A place for keeping papers or digital files together." },
  { word: "file", definition: "A saved piece of information on a computer." },
  { word: "program", definition: "A set of instructions that tells a computer what to do." },
  { word: "code", definition: "Special instructions written for a computer." },
  { word: "app", definition: "A program made for a phone, tablet, or computer." },
  { word: "zero", definition: "The amount of nothing." },
  { word: "one", definition: "The amount after zero and before two." },
  { word: "two", definition: "The amount after one and before three." },
  { word: "three", definition: "The amount after two and before four." },
  { word: "four", definition: "The amount after three and before five." },
  { word: "five", definition: "The amount after four and before six." },
  { word: "six", definition: "The amount after five and before seven." },
  { word: "seven", definition: "The amount after six and before eight." },
  { word: "eight", definition: "The amount after seven and before nine." },
  { word: "nine", definition: "The amount after eight and before ten." },
  { word: "red", definition: "The color of many apples, stop signs, and some fire trucks." },
  { word: "blue", definition: "The color of a clear daytime sky or deep ocean water." },
  { word: "yellow", definition: "The color of the sun in many drawings and ripe bananas." },
  { word: "green", definition: "The color of fresh grass and many leaves." },
  { word: "purple", definition: "A color between blue and red." },
  { word: "violet", definition: "A deep bluish-purple color seen at one end of a rainbow." },
  { word: "indigo", definition: "A dark color between blue and violet." },
  { word: "magenta", definition: "A bright pinkish-purple color." },
  { word: "black", definition: "The darkest color, like a night sky with no lights." },
  { word: "white", definition: "The lightest color, like fresh snow or milk." },
  { word: "gray", definition: "A color between black and white." },
  { word: "brown", definition: "The color of tree bark, soil, or chocolate." },
  { word: "pink", definition: "A light red color." },
  { word: "silver", definition: "A shiny gray color like some coins or metal." },
  { word: "gold", definition: "A rich yellow color like treasure or sunlight." },
  { word: "turquoise", definition: "A blue-green color like some tropical water." },
  { word: "teal", definition: "A dark blue-green color." },
  { word: "beige", definition: "A pale sandy color." },
  { word: "maroon", definition: "A dark red-brown color." },
  { word: "navy", definition: "A very dark blue color." },
  { word: "circle", definition: "A round shape with no corners." },
  { word: "square", definition: "A shape with four equal sides and four corners." },
  { word: "triangle", definition: "A shape with three sides and three corners." },
  { word: "rectangle", definition: "A shape with four sides and four corners, with opposite sides equal." },
  { word: "oval", definition: "A rounded shape like an egg." },
  { word: "diamond", definition: "A shape with four equal sides that looks like a tilted square." },
  { word: "heart", definition: "A shape often used to show love." },
  { word: "shape", definition: "The form or outline of something." },
  { word: "line", definition: "A long mark that can be straight or curved." },
  { word: "curve", definition: "A bend that is not straight." },
  { word: "corner", definition: "The place where two sides meet." },
  { word: "side", definition: "One outer part or edge of something." },
  { word: "edge", definition: "The outside border of something." },
  { word: "cube", definition: "A solid shape with six equal square faces." },
  { word: "sphere", definition: "A round solid shape like a ball." },
  { word: "cone", definition: "A solid shape with a round base and a pointed top." },
  { word: "cylinder", definition: "A solid shape with two round ends and straight sides." },
  { word: "pyramid", definition: "A solid shape with a base and sides that meet at a point." },
  { word: "hair", definition: "Strands that grow on your head." },
  { word: "eye", definition: "The body part used for seeing." },
  { word: "ear", definition: "The body part used to hear sounds." },
  { word: "nose", definition: "The body part used for smelling and breathing." },
  { word: "mouth", definition: "The opening used for eating, speaking, and breathing." },
  { word: "tooth", definition: "A hard white part in your mouth used for biting." },
  { word: "tongue", definition: "A soft body part in your mouth used for tasting and speaking." },
  { word: "neck", definition: "The body part that connects the head to the shoulders." },
  { word: "shoulder", definition: "The body part where the arm joins the body." },
  { word: "arm", definition: "The upper limb between the shoulder and hand." },
  { word: "elbow", definition: "The joint in the middle of the arm." },
  { word: "wrist", definition: "The joint between the hand and arm." },
  { word: "finger", definition: "One of the long parts at the end of a hand." },
  { word: "thumb", definition: "The short thick digit on the side of the hand." },
  { word: "chest", definition: "The front upper part of the body." },
  { word: "back", definition: "The rear side of the body." },
  { word: "waist", definition: "The middle part of the body above the hips." },
  { word: "hip", definition: "The body part at the side of the upper leg." },
  { word: "leg", definition: "The limb used for standing, walking, and running." },
  { word: "knee", definition: "The joint in the middle of the leg." },
  { word: "ankle", definition: "The joint between the foot and leg." },
  { word: "heel", definition: "The back part of the foot." },
  { word: "toe", definition: "One of the small parts at the end of a foot." },
  { word: "skin", definition: "The outer covering of the body." },
  { word: "bone", definition: "A hard part inside the body that gives shape and support." },
  { word: "brain", definition: "The organ inside the head that helps you think and learn." },
  { word: "stomach", definition: "The part inside the body where food starts to break down." },
  { word: "muscle", definition: "A body part that helps you move." },
  { word: "shoelace", definition: "A string used to tie a shoe." },
  { word: "sneaker", definition: "A soft comfortable shoe often worn for sports or everyday use." },
  { word: "boot", definition: "A strong shoe that covers the foot and part of the leg." },
  { word: "sandal", definition: "A light open shoe worn in warm weather." },
  { word: "slipper", definition: "A soft indoor shoe." },
  { word: "shirt", definition: "A piece of clothing worn on the upper body." },
  { word: "jacket", definition: "A short coat worn over clothes." },
  { word: "hoodie", definition: "A warm top with a head covering attached." },
  { word: "sweater", definition: "A warm knitted top." },
  { word: "jeans", definition: "Pants made from sturdy denim cloth." },
  { word: "shorts", definition: "Clothes that cover the legs only to above the knee." },
  { word: "sock", definition: "A soft foot covering worn inside shoes." },
  { word: "glove", definition: "A hand covering with places for fingers." },
  { word: "scarf", definition: "A long piece of cloth worn around the neck." },
  { word: "beanie", definition: "A soft close-fitting hat." },
  { word: "cap", definition: "A hat with a brim in front." },
  { word: "belt", definition: "A strip worn around the waist to hold clothing in place." },
  { word: "collar", definition: "The part around the neck of a shirt or coat." },
  { word: "sleeve", definition: "The part of clothing that covers an arm." },
  { word: "pocketbook", definition: "A small bag used to carry personal things." },
  { word: "bracelet", definition: "A piece of jewelry worn around the wrist." },
  { word: "necklace", definition: "A piece of jewelry worn around the neck." },
  { word: "car", definition: "A road vehicle with wheels used to carry people." },
  { word: "truck", definition: "A large road vehicle used to carry heavy things." },
  { word: "van", definition: "A road vehicle used to carry people or goods." },
  { word: "bus", definition: "A large road vehicle that carries many people." },
  { word: "subway", definition: "A train system that often runs under a city." },
  { word: "tram", definition: "A rail vehicle that moves along city streets." },
  { word: "bicycle", definition: "A two-wheeled vehicle moved by pedals." },
  { word: "scooter", definition: "A small ride with a platform and handlebars." },
  { word: "motorcycle", definition: "A two-wheeled motor vehicle." },
  { word: "airplane", definition: "A flying vehicle with wings and engines." },
  { word: "helicopter", definition: "A flying vehicle with spinning blades on top." },
  { word: "boat", definition: "A vehicle that travels on water." },
  { word: "ship", definition: "A very large boat that carries people or goods." },
  { word: "canoe", definition: "A light narrow boat moved with a paddle." },
  { word: "kayak", definition: "A small narrow boat for one or two people." },
  { word: "submarine", definition: "A vehicle that can travel underwater." },
  { word: "rocket", definition: "A vehicle that blasts into space." },
  { word: "wheel", definition: "A round part that turns to help something move." },
  { word: "brake", definition: "A part used to slow or stop movement." },
  { word: "seatbelt", definition: "A safety strap worn in a vehicle." },
  { word: "traffic", definition: "Cars and other vehicles moving on roads." },
  { word: "teacher", definition: "A person who helps students learn." },
  { word: "doctor", definition: "A person who helps sick or hurt people get better." },
  { word: "nurse", definition: "A person who cares for sick or hurt people." },
  { word: "dentist", definition: "A person who takes care of teeth." },
  { word: "chef", definition: "A person who cooks food, especially in a restaurant." },
  { word: "farmer", definition: "A person who grows crops or cares for farm animals." },
  { word: "pilot", definition: "A person who flies an aircraft." },
  { word: "driver", definition: "A person who controls a car, bus, or truck." },
  { word: "artist", definition: "A person who makes art." },
  { word: "musician", definition: "A person who plays music." },
  { word: "dancer", definition: "A person who moves to music as an art or performance." },
  { word: "actor", definition: "A person who performs in plays, movies, or shows." },
  { word: "builder", definition: "A person who makes houses or other structures." },
  { word: "painter", definition: "A person who covers surfaces with color or makes art." },
  { word: "firefighter", definition: "A person who puts out fires and helps in emergencies." },
  { word: "police", definition: "People whose job is to help keep others safe and follow laws." },
  { word: "mailbox", definition: "A box where letters are sent or collected." },
  { word: "neighbor", definition: "A person who lives near you." },
  { word: "friendship", definition: "A close caring bond between friends." },
  { word: "family", definition: "A group of people related to one another or living together." },
  { word: "team", definition: "A group working or playing together." },
  { word: "crowd", definition: "A large group of people in one place." },
  { word: "second", definition: "A very short unit of time." },
  { word: "minute", definition: "A unit of time made of sixty seconds." },
  { word: "hour", definition: "A unit of time made of sixty minutes." },
  { word: "day", definition: "A period of twenty-four hours." },
  { word: "week", definition: "A period of seven days." },
  { word: "month", definition: "One of the parts a year is divided into." },
  { word: "year", definition: "A period of twelve months." },
  { word: "today", definition: "This day." },
  { word: "tomorrow", definition: "The day after today." },
  { word: "yesterday", definition: "The day before today." },
  { word: "morning", definition: "The early part of the day." },
  { word: "afternoon", definition: "The part of the day after noon." },
  { word: "evening", definition: "The later part of the day before night." },
  { word: "night", definition: "The dark part of the day." },
  { word: "summer", definition: "The hottest season of the year." },
  { word: "autumn", definition: "The season when many leaves change color and fall." },
  { word: "winter", definition: "The coldest season of the year." },
  { word: "happy", definition: "Feeling glad or pleased." },
  { word: "sad", definition: "Feeling unhappy." },
  { word: "angry", definition: "Feeling mad." },
  { word: "brave", definition: "Ready to face something hard or scary." },
  { word: "calm", definition: "Peaceful and not upset." },
  { word: "kind", definition: "Showing care for others." },
  { word: "gentle", definition: "Soft and careful." },
  { word: "quiet", definition: "Making very little sound." },
  { word: "loud", definition: "Making a lot of sound." },
  { word: "proud", definition: "Feeling pleased about something you did or are part of." },
  { word: "shy", definition: "Feeling a little nervous around others." },
  { word: "silly", definition: "Funny in a playful way." },
  { word: "clever", definition: "Quick at learning or solving problems." },
  { word: "curious", definition: "Wanting to know more." },
  { word: "patient", definition: "Able to wait without getting upset." },
  { word: "careful", definition: "Paying close attention to stay safe or do well." },
  { word: "helpful", definition: "Glad to give help." },
  { word: "friendly", definition: "Acting in a warm and kind way." },
  { word: "fair", definition: "Treating people in an equal and right way." },
  { word: "honest", definition: "Telling the truth." },
  { word: "neat", definition: "Clean and well arranged." },
  { word: "messy", definition: "Untidy and not well arranged." },
  { word: "quick", definition: "Moving fast or taking little time." },
  { word: "slow", definition: "Not fast." },
  { word: "soft", definition: "Easy to touch or press." },
  { word: "hard", definition: "Firm and not easy to press or break." },
  { word: "heavy", definition: "Having a lot of weight." },
  { word: "tiny", definition: "Very small." },
  { word: "huge", definition: "Very large." },
  { word: "bright", definition: "Giving or showing a lot of light." },
  { word: "dark", definition: "Having little or no light." },
  { word: "cold", definition: "Having a low temperature." },
  { word: "sweet", definition: "Having a sugary taste." },
  { word: "sour", definition: "Having a sharp taste like a lemon." },
  { word: "salty", definition: "Having the taste of salt." },
  { word: "bitter", definition: "Having a sharp strong taste that is not sweet." },
  { word: "spicy", definition: "Having a hot strong flavor." },
  { word: "smooth", definition: "Even and not rough." },
  { word: "rough", definition: "Not even or smooth." },
  { word: "cleanliness", definition: "The state of being clean." },
  { word: "kindness", definition: "The quality of being caring and nice." },
  { word: "backpacker", definition: "A person carrying a pack while traveling or hiking." },
  { word: "student", definition: "A person who is learning in school." },
  { word: "lesson", definition: "Something taught to help someone learn." },
  { word: "homework", definition: "School work done at home." },
  { word: "quiz", definition: "A short test." },
  { word: "test", definition: "A set of questions used to check learning." },
  { word: "grade", definition: "A score that shows how well work was done." },
  { word: "science", definition: "The study of how the world works." },
  { word: "art", definition: "Pictures, designs, music, or other creative work." },
  { word: "music", definition: "Sounds put together in a way people enjoy." },
  { word: "song", definition: "Words set to music for singing." },
  { word: "drum", definition: "A musical instrument played by hitting it." },
  { word: "guitar", definition: "A musical instrument with strings." },
  { word: "piano", definition: "A musical instrument with keys that are pressed." },
  { word: "violin", definition: "A small string instrument played with a bow." },
  { word: "flute", definition: "A musical instrument played by blowing air across an opening." },
  { word: "trumpet", definition: "A brass instrument played by blowing into it." },
  { word: "soccer", definition: "A sport where players try to kick a ball into a goal." },
  { word: "basketball", definition: "A sport where players try to throw a ball through a hoop." },
  { word: "baseball", definition: "A sport with a bat, a ball, and bases." },
  { word: "tennis", definition: "A sport where players hit a ball back and forth with rackets." },
  { word: "hockey", definition: "A sport where players try to move a puck into a goal." },
  { word: "swimming", definition: "Moving through water using your body." },
  { word: "running", definition: "Moving very fast on foot." },
  { word: "hiking", definition: "Taking a long walk, often in nature." },
  { word: "camping", definition: "Staying outdoors in a tent or simple shelter." },
  { word: "pigeon", definition: "A city bird that often pecks at crumbs." },
  { word: "crow", definition: "A black bird known for being smart." },
  { word: "raven", definition: "A large black bird with a strong beak." },
  { word: "robin", definition: "A small bird often seen with a red chest." },
  { word: "sparrow", definition: "A tiny brown or gray bird often seen near homes." },
  { word: "woodpecker", definition: "A bird that taps tree trunks with its beak." },
  { word: "pelican", definition: "A large water bird with a big pouch under its beak." },
  { word: "seagull", definition: "A bird often seen near the ocean or beach." },
  { word: "canary", definition: "A small yellow songbird." },
  { word: "finch", definition: "A small bird with a short beak." },
  { word: "falcon", definition: "A fast bird that hunts from the sky." },
  { word: "vulture", definition: "A large bird that eats dead animals." },
  { word: "eel", definition: "A long slippery animal that lives in water." },
  { word: "walrus", definition: "A huge sea animal with long tusks." },
  { word: "manatee", definition: "A large gentle water animal that moves slowly." },
  { word: "narwhal", definition: "A sea animal with a long horn-like tooth." },
  { word: "orca", definition: "A black-and-white sea animal that hunts in groups." },
  { word: "bison", definition: "A large shaggy animal with a heavy head and shoulders." },
  { word: "yak", definition: "A hairy animal that lives in cold mountain areas." },
  { word: "alpaca", definition: "A soft-furred animal related to the llama." },
  { word: "sloth", definition: "A tree animal that moves very slowly." },
  { word: "armadillo", definition: "A small animal with a hard shell-like cover." },
  { word: "meerkat", definition: "A small animal that stands upright to look around." },
  { word: "hyena", definition: "A wild animal known for its loud laughing call." },
  { word: "jaguar", definition: "A strong spotted wild cat." },
  { word: "lynx", definition: "A wild cat with pointed ears and a short tail." },
  { word: "wombat", definition: "A short-legged animal from Australia that digs burrows." },
  { word: "platypus", definition: "An unusual Australian animal with a bill and webbed feet." },
  { word: "principal", definition: "The head leader of a school." },
  { word: "chalkboard", definition: "A dark board written on with chalk." },
  { word: "whiteboard", definition: "A smooth board written on with special markers." },
  { word: "binder", definition: "A cover that holds papers together in rings." },
  { word: "worksheet", definition: "A paper with questions or tasks to complete." },
  { word: "calculator", definition: "A tool used to solve math problems." },
  { word: "highlighter", definition: "A bright marker used to make important words stand out." },
  { word: "sharpener", definition: "A tool that makes a pencil point ready to write." },
  { word: "clipboard", definition: "A flat board with a clip for holding papers." },
  { word: "lunchbox", definition: "A container used to carry a meal to school." },
  { word: "cafeteria", definition: "A place in a school where people eat meals." },
  { word: "gymnasium", definition: "A large room used for sports and exercise." },
  { word: "recess", definition: "A break time at school for play and rest." },
  { word: "semester", definition: "One half of a school year in some schools." },
  { word: "schedule", definition: "A plan that shows times for classes or events." },
  { word: "subject", definition: "A topic studied in school, like math or history." },
  { word: "project", definition: "A piece of work done over time." },
  { word: "report", definition: "A written work that shares information." },
  { word: "essay", definition: "A short piece of writing about one idea or topic." },
  { word: "paragraph", definition: "A group of sentences about one main idea." },
  { word: "sentence", definition: "A group of words that shares a complete thought." },
  { word: "spelling", definition: "The correct order of letters in a word." },
  { word: "vocabulary", definition: "All the words a person knows or uses." },
  { word: "dictionary", definition: "A book or tool that explains words and meanings." },
  { word: "encyclopedia", definition: "A book or set of books with facts about many topics." },
  { word: "chapter", definition: "One main part of a book." },
  { word: "fiction", definition: "Stories made from imagination." },
  { word: "nonfiction", definition: "Writing based on real facts and true information." },
  { word: "poem", definition: "A piece of writing that uses rhythm or special word choices." },
  { word: "grammar", definition: "The rules for putting words together the right way." },
  { word: "history", definition: "The study of things that happened in the past." },
  { word: "geography", definition: "The study of places on Earth." },
  { word: "algebra", definition: "A kind of math that uses letters and numbers." },
  { word: "geometry", definition: "A kind of math about shapes, lines, and space." },
  { word: "fraction", definition: "A part of a whole." },
  { word: "decimal", definition: "A number written with a point to show parts of a whole." },
  { word: "equation", definition: "A math statement showing two amounts are equal." },
  { word: "experiment", definition: "A test done to learn something." },
  { word: "laboratory", definition: "A room where science work and tests are done." },
  { word: "microscope", definition: "A tool used to see very tiny things much bigger." },
  { word: "sprint", definition: "Run very fast for a short distance." },
  { word: "dash", definition: "Move quickly from one place to another." },
  { word: "stomp", definition: "Step down hard with your foot." },
  { word: "peek", definition: "Take a quick look." },
  { word: "frown", definition: "Make a face that shows worry or unhappiness." },
  { word: "snicker", definition: "Laugh in a quiet way." },
  { word: "gasp", definition: "Take in air suddenly from surprise." },
  { word: "invent", definition: "Create something new for the first time." },
  { word: "sketch", definition: "Make a quick simple drawing." },
  { word: "doodle", definition: "Draw little shapes or pictures for fun." },
  { word: "organize", definition: "Put things in order." },
  { word: "arrange", definition: "Set things in a chosen order or place." },
  { word: "attach", definition: "Join one thing to another." },
  { word: "detach", definition: "Take one thing away from another." },
  { word: "unfold", definition: "Open something that was folded." },
  { word: "crumple", definition: "Press into a wrinkled ball or mess." },
  { word: "scribble", definition: "Write or draw in a quick messy way." },
  { word: "mutter", definition: "Speak in a low hard-to-hear voice." },
  { word: "cheer", definition: "Shout with joy or support." },
  { word: "applaud", definition: "Clap to show praise." },
  { word: "salute", definition: "Raise your hand in a sign of respect." },
  { word: "greet", definition: "Welcome someone when they arrive." },
  { word: "offer", definition: "Hold out or give something to someone." },
  { word: "accept", definition: "Say yes to receiving something." },
  { word: "refuse", definition: "Say no to something offered or asked." },
  { word: "rescue", definition: "Save from danger." },
  { word: "drag", definition: "Pull something along the ground." },
  { word: "twirl", definition: "Spin around lightly." },
  { word: "drift", definition: "Move slowly without much control." },
  { word: "glide", definition: "Move smoothly and easily." },
  { word: "shuffle", definition: "Walk with short dragging steps." },
  { word: "sprinkle", definition: "Drop small bits or drops over something." },
  { word: "slice", definition: "Cut into thin flat pieces." },
  { word: "chop", definition: "Cut into smaller parts." },
  { word: "connect", definition: "Join things together." },
  { word: "separate", definition: "Pull apart or keep apart." },
  { word: "sprout", definition: "Begin to grow." },
  { word: "sink", definition: "Go down below the surface." },
  { word: "twinkle", definition: "Shine with small quick flashes of light." },
  { word: "gallop", definition: "Run fast like a horse." },
  { word: "tiptoe", definition: "Walk quietly on your toes." },
  { word: "canada", definition: "A large country in North America known for maple leaves and cold winters." },
  { word: "mexico", definition: "A country south of the United States known for tacos, beaches, and ancient ruins." },
  { word: "brazil", definition: "A large South American country known for rainforests and soccer." },
  { word: "argentina", definition: "A South American country known for tango and wide grasslands." },
  { word: "france", definition: "A European country known for art, fashion, and the Eiffel Tower." },
  { word: "spain", definition: "A European country known for sunny weather, dance, and soccer." },
  { word: "italy", definition: "A European country known for pasta, pizza, and ancient buildings." },
  { word: "germany", definition: "A European country known for castles, forests, and engineering." },
  { word: "egypt", definition: "An African country known for pyramids and the Nile River." },
  { word: "nigeria", definition: "A large African country with many people and languages." },
  { word: "kenya", definition: "An African country known for wildlife and long-distance runners." },
  { word: "india", definition: "A large Asian country known for many languages, foods, and festivals." },
  { word: "china", definition: "A very large Asian country with a long history and the Great Wall." },
  { word: "japan", definition: "An island country in Asia known for sushi, trains, and cherry blossoms." },
  { word: "australia", definition: "A country and continent known for kangaroos and the Outback." },
  { word: "toronto", definition: "A big Canadian city known for the CN Tower." },
  { word: "vancouver", definition: "A Canadian city near mountains and the ocean." },
  { word: "montreal", definition: "A Canadian city known for French culture and festivals." },
  { word: "london", definition: "A major city in England known for Big Ben and double-decker buses." },
  { word: "paris", definition: "A famous French city known for the Eiffel Tower and art museums." },
  { word: "rome", definition: "A historic Italian city with ancient ruins and fountains." },
  { word: "tokyo", definition: "A very large Japanese city known for bright lights and busy streets." },
  { word: "seoul", definition: "A major South Korean city known for technology and pop music." },
  { word: "sydney", definition: "A major Australian city known for its harbor and opera house." },
  { word: "cairo", definition: "A large city in Egypt near the pyramids." },
  { word: "mumbai", definition: "A large Indian city by the sea." },
  { word: "beijing", definition: "A major Chinese city known for palaces and long history." },
  { word: "shanghai", definition: "A big Chinese city known for tall buildings and a busy waterfront." },
  { word: "delhi", definition: "A major Indian city with many markets and historic places." },
  { word: "nairobi", definition: "A major Kenyan city known for being close to wildlife parks." },
  { word: "berlin", definition: "A major German city known for history and museums." },
  { word: "madrid", definition: "A major Spanish city known for art and soccer." },
  { word: "dubai", definition: "A city known for very tall buildings and desert heat." },
  { word: "ottawa", definition: "The capital city of Canada." },
  { word: "moscow", definition: "A major Russian city known for onion-shaped domes and snowy winters." },
  { word: "lagos", definition: "A very large city in Nigeria near the coast." }
];